Repository konveyor/move2kube, pull requests merged in 2020-12, with the labels that each got.

#315 feat: add support for automatic creation of release notes
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .grenrc.js
  Makefile
  scripts/builddist.go
Labels: enhancement

#317 fix: personal access token name
  .github/workflows/tag.yml
Labels: bug

#318 fix: give gren the tag and also update the upload assets action to a working version
  .github/workflows/release.yml
Labels: bug

#319 fix: calculation of tag and update the template for creating release
  .github/workflows/release.yml
  .grenrc.js
Labels: bug

#320 feat: ask which translation types the user is interested in
  .grenrc.js
  internal/move2kube/planner.go
  internal/qaengine/engine.go
Labels: enhancement

#321 fix: the triggering of releases in other repos
  .github/workflows/assignproject.yml
  .github/workflows/release.yml
Labels: bug

#322 fix: create temporary image so we can run move2kube-tests
  .github/workflows/assignproject.yml
  .github/workflows/release.yml
Labels: bug

#324 fix: use an action to get the go version instead of hardcoding it
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  Dockerfile
  Makefile
Labels: bug

#325 feat: add publish release draft workflow
  .github/workflows/publish.yml
Labels: enhancement

#329 feat: label pull requests based on their title
  .github/workflows/labelpr.yml
Labels: enhancement

#330 ci: added support for specifying commit and previous tag while releasing
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: ci

#331 chore: add each valid PR type to a group in release notes
  .grenrc.js
Labels: chore

#332 feat: create the translate plugin for kubectl
  Makefile
  cmd/common/utils.go
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/collect.go
  cmd/move2kube/move2kube.go
  cmd/move2kube/plan.go
  cmd/move2kube/translate.go
  cmd/move2kube/version.go
Labels: feat

#333 chore: release the plugin when we make a non prerelease
  .github/workflows/release.yml
Labels: chore

#340 fix: the createRef function takes a string for the SHA so we need double quotes
  .github/workflows/labelpr.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  contributing.md
Labels: fix

#341 chore: workflow changes to accomodate the new release branches
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  Makefile
Labels: chore

#343 revert: Delta builds not working with make build
  Makefile
Labels: revert

#344 fix: Fix path computation when cf manifest has a path
  internal/source/cfmanifest2kube.go
Labels: fix

#346 docs: Update install instructions
  README.md
Labels: docs

#349 docs: Point usage links to website
  README.md
Labels: docs

#350 feat: Make option for using default answers visible in help
  cmd/move2kube/translate.go
Labels: feat

#351 fix: If cf app path directory is missing, assume manifest path as app source location
  internal/source/cfmanifest2kube.go
Labels: fix

#352 chore: Cleanup go.mod and go.sum
  go.mod
  go.sum
Labels: chore

#354 feat: write release information to a file
  .github/workflows/releaseinfo.yml
  .gitignore
Labels: feat

#355 feat: initial version of the release UI
  _data/releaseinfo.json
  _includes/releaseinfo.html
  assets/js/asciinema-player.js
  assets/js/internalpages/releaseui-bundle.js
  assets/js/internalpages/releaseui.js
  assets/js/internalpages/releaseui.js.map
  assets/ts/internalpages/releaseui.ts
  docs/installation/releases.html
  internalpages/releases.html
  package-lock.json
  package.json
  tsconfig.json
Labels: feat

#356 fix: show error when credentials are wrong
  assets/js/internalpages/releaseui-bundle.js
  assets/js/internalpages/releaseui.js
  assets/js/internalpages/releaseui.js.map
  assets/ts/internalpages/releaseui.ts
Labels: fix

#357 ci: create branch if necessary in the release workflow
  .github/workflows/release.yml
  .grenrc.js
Labels: ci

#359 ci: change publish workflow to handle the data sent from the UI
  .github/workflows/publish.yml
Labels: ci

#360 ci: clean up workflows to work together across multiple repos
  .github/workflows/assignproject.yml
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
Labels: ci

#353 feat: Save generated scripts in separate directory
  internal/assets/constants.go
  internal/common/constants.go
  internal/containerizer/scripts/constants.go
  internal/metadata/clusters/constants.go
  internal/source/data/constants.go
  internal/transformer/cicdtransformer.go
  internal/transformer/k8stransformer.go
  internal/transformer/knativetransformer.go
  internal/transformer/templates/CopySources.sh
  internal/transformer/templates/K8sReadme.md
  internal/transformer/templates/KnativeReadme.md
  internal/transformer/templates/constants.go
  internal/transformer/transformer.go
Labels: feat

#361 fix: Change default dir for image to workspace
  Dockerfile
Labels: fix

#362 docs: Add doc for all-in-one container based ui bring up
  .github/workflows/release.yml
  README.md
Labels: docs

#364 feat: Change base image to fedora
  Dockerfile
  scripts/installdeps.sh
Labels: feat

#365 fix: Optimize docker image size by cleaning up each layer
  Dockerfile
Labels: fix

#366 feat: Support CNB without mounting docker sock using podman
  Dockerfile
  containerconfig/containers.conf
  containerconfig/storage.conf
  internal/containerizer/cnb/containerruntimeprovider.go
  internal/containerizer/cnb/dockerapiprovider.go
  internal/containerizer/cnb/dockerapiprovider_test.go
Labels: feat

#367 fix: Use overlay storage to reduce space occupied by pulled images
  containerconfig/storage.conf
Labels: fix

#368 fix: Add support for older kernels which does not support metacopy flag in mount
  containerconfig/storage.conf
Labels: fix

#369 ci: minor fixes to allow release
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: ci

#370 ci: fix bug where the 2 args were being treated as a single arg and passed to GREN
  .github/workflows/release.yml
Labels: ci

#371 ci: workaround for a bug in the github API
  .github/workflows/release.yml
Labels: ci
