Repository konveyor/move2kube, pull requests merged in 2021-11, with the labels that each got.

#619 feat: Set default maven profiles based on activebydefault flag in pom
  assets/inbuilt/transformers/dockerfile/java/jar/templates/Dockerfile.embedded
  transformer/classes/dockerfile/java/mavenanalyser.go
  transformer/classes/dockerfile/java/springbootutils.go
  types/transformer/artifacts/springboot.go
Labels: feat

#622 feat: Unified return for named and unnamed tranformerplans in detect functions in transformers
  lib/planner.go
  transformer/classes/cloudfoundry/cloudfoundryanalyser.go
  transformer/classes/cnb/cnbcontainerizer.go
  transformer/classes/cnb/cnbgenerator.go
  transformer/classes/compose/composeanalyser.go
  transformer/classes/compose/composegenerator.go
  transformer/classes/container/containerimagesbuildscript.go
  transformer/classes/container/containerimagespushscript.go
  transformer/classes/dockerfile/dockerfilebuildscriptgenerator.go
  transformer/classes/dockerfile/dockerfiledetector.go
  transformer/classes/dockerfile/dockerfileparser.go
  transformer/classes/dockerfile/dotnet5dockerfilegenerator.go
  transformer/classes/dockerfile/golangdockerfilegenerator.go
  transformer/classes/dockerfile/java/eurekareplaceengine.go
  transformer/classes/dockerfile/java/jaranalyser.go
  transformer/classes/dockerfile/java/mavenanalyser.go
  transformer/classes/dockerfile/java/zuulanalyser.go
  transformer/classes/dockerfile/nodejsdockerfilegenerator.go
  transformer/classes/dockerfile/phpdockerfilegenerator.go
  transformer/classes/dockerfile/windows/consoleappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/silverlightwebappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/webappdockerfilegenerator.go
  transformer/classes/external/executable.go
  transformer/classes/external/starlark.go
  transformer/classes/external/types.go
  transformer/classes/kubernetes/buildconfiggenerator.go
  transformer/classes/kubernetes/knativegenerator.go
  transformer/classes/kubernetes/kubernetesgenerator.go
  transformer/classes/kubernetes/parameterizer.go
  transformer/classes/kubernetes/tektongenerator.go
  transformer/classes/readmegenerator.go
  transformer/classes/s2i/s2igenerator.go
  transformer/servicenamer.go
  transformer/transformer.go
  transformer/utils.go
  types/plan/plan.go
  types/transformer/output.go
  types/transformer/plan.go
Labels: feat

#623 fix: Fix output parsing in executable transformer and fix pom parsing
  transformer/classes/dockerfile/java/mavenanalyser.go
  transformer/classes/external/executable.go
  transformer/utils.go
  types/source/maven/pom.go
Labels: fix

#630 fix: set umask to 0 so that file and directory permissions are set correctly
  cmd/move2kube/move2kube.go
Labels: fix

#631 feat: Change transformer interface to use only DirectoryDetect controlled by parameters in transformer yaml
  assets/filepermissions.yaml
  assets/inbuilt/transformers/cloudfoundry/cloudfoundry.yaml
  assets/inbuilt/transformers/cnb/cnbgenerator/cnbgenerator.yaml
  assets/inbuilt/transformers/compose/composeanalyser/composeanalyser.yaml
  assets/inbuilt/transformers/compose/composegenerator/composegenerator.yaml
  assets/inbuilt/transformers/containers/containerimagesbuildscript/containerimagesbuildscript.yaml
  assets/inbuilt/transformers/containers/containerimagespushscript/containerimagespushscript.yaml
  assets/inbuilt/transformers/dockerfile/dockerfiledetector/dockerfiledetector.yaml
  assets/inbuilt/transformers/dockerfile/dockerfileparser/dockerfileparser.yaml
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/dockerfilebuildscriptgenerator.yaml
  assets/inbuilt/transformers/dockerfile/java/zuul/zuulanalyser.yaml
  assets/inbuilt/transformers/kubernetes/buildconfig/buildconfig.yaml
  assets/inbuilt/transformers/kubernetes/knative/knative.yaml
  assets/inbuilt/transformers/kubernetes/kubernetes/kubernetes.yaml
  assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
  assets/inbuilt/transformers/kubernetes/tekton/tekton.yaml
  assets/inbuilt/transformers/readmegenerator/readmegenerator.yaml
  assets/inbuilt/transformers/s2i/buildscriptgenerator/s2ibuildscriptgenerator.yaml
  transformer/classes/cloudfoundry/cloudfoundryanalyser.go
  transformer/classes/cnb/cnbcontainerizer.go
  transformer/classes/cnb/cnbgenerator.go
  transformer/classes/compose/composeanalyser.go
  transformer/classes/compose/composegenerator.go
  transformer/classes/container/containerimagesbuildscript.go
  transformer/classes/container/containerimagespushscript.go
  transformer/classes/dockerfile/dockerfilebuildscriptgenerator.go
  transformer/classes/dockerfile/dockerfiledetector.go
  transformer/classes/dockerfile/dockerfileparser.go
  transformer/classes/dockerfile/dotnet5dockerfilegenerator.go
  transformer/classes/dockerfile/golangdockerfilegenerator.go
  transformer/classes/dockerfile/java/eurekareplaceengine.go
  transformer/classes/dockerfile/java/jaranalyser.go
  transformer/classes/dockerfile/java/mavenanalyser.go
  transformer/classes/dockerfile/java/zuulanalyser.go
  transformer/classes/dockerfile/nodejsdockerfilegenerator.go
  transformer/classes/dockerfile/phpdockerfilegenerator.go
  transformer/classes/dockerfile/windows/consoleappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/silverlightwebappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/webappdockerfilegenerator.go
  transformer/classes/external/executable.go
  transformer/classes/external/starlark.go
  transformer/classes/kubernetes/buildconfiggenerator.go
  transformer/classes/kubernetes/knativegenerator.go
  transformer/classes/kubernetes/kubernetesgenerator.go
  transformer/classes/kubernetes/parameterizer.go
  transformer/classes/kubernetes/tektongenerator.go
  transformer/classes/readmegenerator.go
  transformer/classes/s2i/s2igenerator.go
  transformer/transformer.go
  transformer/utils.go
  types/transformer/transformer.go
Labels: feat

#632 refactor: Remove containerization support using s2i and cnb
  Dockerfile
  README.md
  assets/filepermissions.yaml
  assets/inbuilt/transformers/cnb/cfcnb/cfcnb.yaml
  assets/inbuilt/transformers/cnb/cnbgenerator/cnbgenerator.yaml
  assets/inbuilt/transformers/cnb/cnbgenerator/templates/cnbbuild.bat
  assets/inbuilt/transformers/cnb/cnbgenerator/templates/cnbbuild.sh
  assets/inbuilt/transformers/cnb/gcrcnb/gcrcnb.yaml
  assets/inbuilt/transformers/s2i/buildscriptgenerator/s2ibuildscriptgenerator.yaml
  assets/inbuilt/transformers/s2i/buildscriptgenerator/templates/s2ibuild.bat
  assets/inbuilt/transformers/s2i/buildscriptgenerator/templates/s2ibuild.sh
  assets/inbuilt/transformers/s2i/golang/golang.yaml
  assets/inbuilt/transformers/s2i/golang/m2kdetect.sh
  assets/inbuilt/transformers/s2i/golang/templates/$.s2i/environment
  assets/inbuilt/transformers/s2i/nodejs/nodejs.star
  assets/inbuilt/transformers/s2i/nodejs/nodejs.yaml
  assets/inbuilt/transformers/s2i/nodejs/templates/$.s2i/environment
  assets/inbuilt/transformers/s2i/php/m2kdetect.sh
  assets/inbuilt/transformers/s2i/php/php.yaml
  assets/inbuilt/transformers/s2i/php/templates/$.s2i/environment
  assets/inbuilt/transformers/s2i/python/m2kdetect.sh
  assets/inbuilt/transformers/s2i/python/python.yaml
  assets/inbuilt/transformers/s2i/python/templates/$.s2i/environment
  assets/inbuilt/transformers/s2i/ruby/m2kdetect.sh
  assets/inbuilt/transformers/s2i/ruby/ruby.yaml
  assets/inbuilt/transformers/s2i/ruby/templates/$.s2i/environment
  transformer/classes/cnb/cnbcontainerizer.go
  transformer/classes/cnb/cnbgenerator.go
  transformer/classes/s2i/s2igenerator.go
  transformer/transformer.go
  types/transformer/artifacts/cnb.go
  types/transformer/artifacts/s2i.go
Labels: refactor

#633 feat: Make transformers create artifacts in detect
  common/constants.go
  lib/planner.go
  transformer/classes/cloudfoundry/cloudfoundryanalyser.go
  transformer/classes/compose/composeanalyser.go
  transformer/classes/compose/composegenerator.go
  transformer/classes/container/containerimagesbuildscript.go
  transformer/classes/container/containerimagespushscript.go
  transformer/classes/dockerfile/dockerfilebuildscriptgenerator.go
  transformer/classes/dockerfile/dockerfiledetector.go
  transformer/classes/dockerfile/dockerfileparser.go
  transformer/classes/dockerfile/dotnet5dockerfilegenerator.go
  transformer/classes/dockerfile/golangdockerfilegenerator.go
  transformer/classes/dockerfile/java/eurekareplaceengine.go
  transformer/classes/dockerfile/java/jaranalyser.go
  transformer/classes/dockerfile/java/mavenanalyser.go
  transformer/classes/dockerfile/java/zuulanalyser.go
  transformer/classes/dockerfile/nodejsdockerfilegenerator.go
  transformer/classes/dockerfile/phpdockerfilegenerator.go
  transformer/classes/dockerfile/windows/consoleappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/silverlightwebappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/webappdockerfilegenerator.go
  transformer/classes/external/executable.go
  transformer/classes/external/starlark.go
  transformer/classes/kubernetes/buildconfiggenerator.go
  transformer/classes/kubernetes/knativegenerator.go
  transformer/classes/kubernetes/kubernetesgenerator.go
  transformer/classes/kubernetes/parameterizer.go
  transformer/classes/kubernetes/tektongenerator.go
  transformer/classes/readmegenerator.go
  transformer/servicenamer.go
  transformer/transformer.go
  transformer/utils.go
  types/plan/plan.go
  types/transformer/plan.go
Labels: feat

#621 feat: Add Golang-based transformer for Ruby
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/ruby/m2kdetect.sh
  assets/inbuilt/transformers/dockerfile/ruby/ruby.yaml
  assets/inbuilt/transformers/dockerfile/ruby/templates/Dockerfile
  samples/ruby/config.ru
  samples/ruby/ruby.rb
  transformer/classes/dockerfile/rubydockerfilegenerator.go
  transformer/transformer.go
Labels: feat

#634 fix: Replace "Dockerfile" string with the constant string
  transformer/classes/compose/composeanalyser.go
  transformer/classes/dockerfile/dotnet5dockerfilegenerator.go
  transformer/classes/dockerfile/golangdockerfilegenerator.go
  transformer/classes/dockerfile/java/jaranalyser.go
  transformer/classes/dockerfile/nodejsdockerfilegenerator.go
  transformer/classes/dockerfile/phpdockerfilegenerator.go
  transformer/classes/dockerfile/utils.go
  transformer/classes/dockerfile/windows/consoleappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/silverlightwebappdockerfilegenerator.go
  transformer/classes/dockerfile/windows/webappdockerfilegenerator.go
Labels: fix

#635 feat: Allow for custom config merge functions
  README.md
  common/utils.go
  transformer/transformer.go
  transformer/utils.go
  troubleshooting-dev.md
  types/info/versioninfo.go
  types/ir/ir.go
  types/transformer/artifacts/config.go
  types/transformer/config.go
Labels: feat

#636 feat: Support merging artifacts on a per transformer basis
  assets/inbuilt/transformers/cloudfoundry/cloudfoundry.yaml
  assets/inbuilt/transformers/compose/composeanalyser/composeanalyser.yaml
  assets/inbuilt/transformers/compose/composegenerator/composegenerator.yaml
  assets/inbuilt/transformers/containers/containerimagesbuildscript/containerimagesbuildscript.yaml
  assets/inbuilt/transformers/containers/containerimagespushscript/containerimagespushscript.yaml
  assets/inbuilt/transformers/dockerfile/django/django.yaml
  assets/inbuilt/transformers/dockerfile/dockerfiledetector/dockerfiledetector.yaml
  assets/inbuilt/transformers/dockerfile/dockerfileparser/dockerfileparser.yaml
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/dockerfilebuildscriptgenerator.yaml
  assets/inbuilt/transformers/dockerfile/dotnet5/dotnet5.yaml
  assets/inbuilt/transformers/dockerfile/golang/golang.yaml
  assets/inbuilt/transformers/dockerfile/java/eurekareplaceengine/eureka.yaml
  assets/inbuilt/transformers/dockerfile/java/jar/jar.yaml
  assets/inbuilt/transformers/dockerfile/java/maven/maven.yaml
  assets/inbuilt/transformers/dockerfile/java/zuul/zuulanalyser.yaml
  assets/inbuilt/transformers/dockerfile/nodejs/nodejs.yaml
  assets/inbuilt/transformers/dockerfile/php/php.yaml
  assets/inbuilt/transformers/dockerfile/python/python.yaml
  assets/inbuilt/transformers/dockerfile/ruby/ruby.yaml
  assets/inbuilt/transformers/dockerfile/rust/rust.yaml
  assets/inbuilt/transformers/dockerfile/windows/winconsole/winconsole.yaml
  assets/inbuilt/transformers/dockerfile/windows/winsilverlightweb/winsilverlightweb.yaml
  assets/inbuilt/transformers/dockerfile/windows/winweb/winweb.yaml
  assets/inbuilt/transformers/kubernetes/buildconfig/buildconfig.yaml
  assets/inbuilt/transformers/kubernetes/knative/knative.yaml
  assets/inbuilt/transformers/kubernetes/kubernetes/kubernetes.yaml
  assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
  assets/inbuilt/transformers/kubernetes/tekton/tekton.yaml
  assets/inbuilt/transformers/readmegenerator/readmegenerator.yaml
  transformer/transformer.go
  transformer/utils.go
  types/transformer/transformer.go
Labels: feat

#637 feat: Enable path templates in path mappings
  assets/inbuilt/transformers/kubernetes/kubernetes/kubernetes.yaml
  assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
  common/utils.go
  environment/environment.go
  lib/parameterizer.go
  lib/testdata/parameterizers/pack.yaml
  parameterizer/parameterizer.go
  transformer/classes/kubernetes/kubernetesgenerator.go
  transformer/classes/kubernetes/parameterizer.go
  transformer/processors.go
  types/parameterizer/parameterizer.go
  types/transformer/pathmapping.go
Labels: feat

#638 feat: Expose path configurations in transformers
  assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
  environment/environment.go
  filesystem/processor.go
  filesystem/templatecopy.go
  transformer/classes/dockerfile/dockerfileparser.go
  transformer/classes/kubernetes/kubernetesgenerator.go
  transformer/classes/kubernetes/parameterizer.go
Labels: feat

#639 feat: Expose helm-chart name
  apiresource/service.go
  filesystem/processor.go
  filesystem/templatecopy.go
  transformer/classes/kubernetes/kubernetesgenerator.go
Labels: feat

#641 fix: Changed project name and paths to service name and paths in k8s-gen and paramaterizer
  assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
  transformer/classes/dockerfile/dockerfileparser.go
  transformer/classes/kubernetes/kubernetesgenerator.go
  transformer/classes/kubernetes/parameterizer.go
Labels: fix

#644 fix: fix error in IR merge
  types/ir/ir.go
Labels: fix

#643 feat: CustomTemplate path mapping to switch template-delimiter
  cmd/move2kube/transform.go
  common/utils.go
  environment/environment.go
  filesystem/templatecopy.go
  lib/planner.go
  lib/utils.go
  transformer/processors.go
  types/transformer/pathmapping.go
Labels: feat

#646 feat: Added template resolution for file paths
  filesystem/templatecopy.go
Labels: feat

#647 feat: Make ingress name configurable in kubernetes transformer
  apiresource/service.go
  assets/inbuilt/transformers/kubernetes/kubernetes/kubernetes.yaml
  common/constants.go
  common/utils.go
  transformer/classes/kubernetes/kubernetesgenerator.go
  transformer/classes/kubernetes/parameterizer.go
Labels: feat

#648 feat: Delete path-mapping to allow for file/folder deletion
  transformer/classes/external/starlark.go
  transformer/processors.go
  types/transformer/pathmapping.go
Labels: feat

#640 feat: Add golang-based transformer for Python and Django
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/django/django.yaml
  assets/inbuilt/transformers/dockerfile/django/m2kdetect.sh
  assets/inbuilt/transformers/dockerfile/django/templates/Dockerfile
  assets/inbuilt/transformers/dockerfile/python/m2kdetect.sh
  assets/inbuilt/transformers/dockerfile/python/python.yaml
  assets/inbuilt/transformers/dockerfile/python/templates/Dockerfile
  common/constants.go
  common/utils.go
  transformer/classes/dockerfile/pythondockerfilegenerator.go
  transformer/transformer.go
Labels: feat

#651 feat: Set umask only in non-windows platforms
  cmd/move2kube/move2kube.go
  cmd/move2kube/umask.go
Labels: feat

#652 feat: Add support for jar file containerization
  assets/inbuilt/transformers/dockerfilegenerator/java/jar/templates/Dockerfile.embedded
  common/constants.go
  common/utils.go
  transformer/dockerfilegenerator/java/jaranalyser.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  types/transformer/artifacts/java.go
Labels: feat

#653 feat: Use streaming file copy
  common/utils.go
  filesystem/delta.go
  filesystem/merger.go
  filesystem/replicator.go
  filesystem/templatecopy.go
  filesystem/utils.go
Labels: feat

#654 fix: Updated the dotnet core versions supported by Move2Kube
  transformer/dockerfilegenerator/dotnet5dockerfiletransformer.go
Labels: fix
