Repository konveyor/move2kube, pull requests merged in 2021-06, with the labels that each got.

#506 fix: the case of SetString on values of map[string]string
  types/plan/planutils.go
Labels: fix

#509 chore: Update kubernetes lib version to 21.2
  environment/container/dockerengine.go
  go.mod
  go.sum
  internal/k8sschema/k8sschema.go
Labels: chore

#510 feat: Add cloud foundry support
  assets/constants.go
  assets/transformers/cloudfoundry/cloudfoundry.yaml
  cmd/common/utils.go
  go.mod
  go.sum
  internal/transformer/classes/analysers/cloudfoundry.go
  internal/transformer/transformer.go
Labels: feat

#511 feat: Add detect support for existing dockerfiles
  api/transformer.go
  assets/constants.go
  assets/transformers/dockerfiledetector/dockerfiledetector.yaml
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  environment/container/dockerengine.go
  environment/peercontainer.go
  go.mod
  go.sum
  internal/transformer/classes/analysers/cloudfoundry.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/analysers/composeanalyser.go
  internal/transformer/classes/analysers/dockerfile.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/classes/generators/cnbgenerator.go
  internal/transformer/servicenamer.go
  internal/transformer/transformer.go
  internal/transformer/utils.go
  types/plan/plan.go
  types/transformer/artifacts.go
Labels: feat

#514 feat: Add support for transform as executable
  environment/container/dockerengine.go
  environment/container/utils.go
  environment/environment.go
  environment/peercontainer.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/transformer.go
  types/transformer/pathmapping.go
Labels: feat

#518 feat: Add support for qa for external transformers using grpc
  assets/constants.go
  environment/container/container.go
  environment/container/dockerengine.go
  environment/environment.go
  environment/local.go
  environment/peercontainer.go
  environment/utils.go
  go.mod
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/transformer.go
  qaengine/engine.go
  qaengine/grpcreceiver.go
  types/qaengine/problem.go
  types/qaengine/qagrpc/fetchanswer.pb.go
  types/qaengine/qagrpc/fetchanswer.proto
  types/qaengine/qagrpc/fetchanswer_grpc.pb.go
Labels: feat

#525 fix: Fix behavior when using -s in transform
  cmd/move2kube/transform.go
  filesystem/templatecopy_test.go
  internal/common/pathconverters/pathconverters_test.go
  types/plan/plan.go
  types/plan/planutils.go
Labels: fix

#526 feat: Suggest transform command when translate is used
  cmd/move2kube/transform.go
Labels: feat

#527 fix: Fix tests where applicable for the new framework
  Makefile
  environment/container/dockerengine_test.go
  internal/configuration/clustermdloader_test.go
  internal/transformer/transformer.go
Labels: fix

#529 feat: add the parameterize command
  .gitignore
  cmd/common/utils.go
  cmd/move2kube/move2kube.go
  cmd/move2kube/parameterize.go
  go.sum
  internal/common/utils.go
  parameterizer/common/utils.go
  parameterizer/common/utils_test.go
  parameterizer/parameterizer.go
  parameterizer/parameterizer_test.go
  parameterizer/testdata/k8s-resources/dep-v1.yaml
  parameterizer/testdata/k8s-resources/dep-v1beta1.yaml
  parameterizer/testdata/k8s-resources/namespace-v1.yaml
  parameterizer/testdata/parameterizers/p1.yaml
  parameterizer/testdata/parameterizers/p2.yaml
  parameterizer/testdata/parameterizers/pack.yaml
  parameterizer/testdata/want/helm-chart/myproject/Chart.yaml
  parameterizer/testdata/want/helm-chart/myproject/templates/dep-v1.yaml
  parameterizer/testdata/want/helm-chart/myproject/templates/dep-v1beta1.yaml
  parameterizer/testdata/want/helm-chart/myproject/templates/namespace-v1.yaml
  parameterizer/testdata/want/helm-chart/myproject/values-dev.yaml
  parameterizer/testdata/want/helm-chart/myproject/values-prod.yaml
  parameterizer/testdata/want/helm-chart/myproject/values-staging.yaml
  parameterizer/testdata/want/kustomize/base/dep-v1.yaml
  parameterizer/testdata/want/kustomize/base/dep-v1beta1.yaml
  parameterizer/testdata/want/kustomize/base/kustomization.yaml
  parameterizer/testdata/want/kustomize/base/namespace-v1.yaml
  parameterizer/testdata/want/kustomize/overlays/dev/apps-v1-deployment-nginx.yaml
  parameterizer/testdata/want/kustomize/overlays/dev/extensions-v1beta1-deployment-javaspringapp.yaml
  parameterizer/testdata/want/kustomize/overlays/dev/kustomization.yaml
  parameterizer/testdata/want/kustomize/overlays/prod/apps-v1-deployment-nginx.yaml
  parameterizer/testdata/want/kustomize/overlays/prod/extensions-v1beta1-deployment-javaspringapp.yaml
  parameterizer/testdata/want/kustomize/overlays/prod/kustomization.yaml
  parameterizer/testdata/want/kustomize/overlays/staging/apps-v1-deployment-nginx.yaml
  parameterizer/testdata/want/kustomize/overlays/staging/extensions-v1beta1-deployment-javaspringapp.yaml
  parameterizer/testdata/want/kustomize/overlays/staging/kustomization.yaml
  parameterizer/testdata/want/m2kconfig.yaml
  parameterizer/testdata/want/m2kqacache.yaml
  parameterizer/testdata/want/openshift-template/parameters-dev.yaml
  parameterizer/testdata/want/openshift-template/parameters-prod.yaml
  parameterizer/testdata/want/openshift-template/parameters-staging.yaml
  parameterizer/testdata/want/openshift-template/template.yaml
  parameterizer/types/types.go
  types/qaengine/config.go
Labels: feat

#530 fix: fix lint errors
  api/transformer.go
  assets/assets.go
  environment/container/container.go
  environment/container/dockerengine.go
  environment/container/dockerengine_test.go
  environment/environment.go
  environment/local.go
  environment/peercontainer.go
  filesystem/delta.go
  filesystem/merger.go
  filesystem/replicator.go
  filesystem/templatecopy.go
  internal/apiresource/buildconfig.go
  internal/apiresource/utils.go
  internal/common/constants.go
  internal/common/pathconverters/pathconverters.go
  internal/common/utils.go
  internal/configuration/clustermdloader.go
  internal/transformer/classes/analysers/cloudfoundryanalyser.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/analysers/composeanalyser.go
  internal/transformer/classes/analysers/dockerfileanalyser.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/classes/generators/buildconfiggenerator.go
  internal/transformer/classes/generators/cnbgenerator.go
  internal/transformer/classes/generators/composegenerator.go
  internal/transformer/classes/generators/knativegenerator.go
  internal/transformer/classes/generators/kubernetesgenerator.go
  internal/transformer/classes/generators/tektongenerator.go
  internal/transformer/classes/metaartifacts/containerimagepushscript.go
  internal/transformer/classes/metaartifacts/readmegenerator.go
  internal/transformer/servicenamer.go
  internal/transformer/transformer.go
  internal/transformer/utils.go
  parameterizer/common/utils.go
  parameterizer/parameterizer.go
  parameterizer/types/types.go
  qaengine/engine.go
  qaengine/grpcreceiver.go
  types/environment/container.go
  types/environment/exec.go
  types/ir/ir.go
  types/plan/plan.go
  types/qaengine/problem.go
  types/transformer/artifact.go
  types/transformer/artifacts/artifacts.go
  types/transformer/artifacts/buildscript.go
  types/transformer/artifacts/cloudfoundry.go
  types/transformer/artifacts/cnb.go
  types/transformer/artifacts/containerbuild.go
  types/transformer/artifacts/dockerfileartifact.go
  types/transformer/artifacts/imagepushscript.go
  types/transformer/artifacts/newimages.go
  types/transformer/artifacts/plan.go
  types/transformer/artifacts/service.go
  types/transformer/pathmapping.go
  types/transformer/transformer.go
Labels: fix

#531 fix: Prevent crash when all transformers for a service become unselected
  api/planner.go
Labels: fix

#532 fix: set modified timestamp during filecopy to prevent repeated copy
  filesystem/delta.go
  filesystem/merger.go
  filesystem/processor.go
  filesystem/replicator.go
  filesystem/utils.go
Labels: fix
