Repository konveyor/move2kube, pull requests merged in 2021-01, with the labels that each got.

#376 chore: add brew install instructions
  docs/installation/command-line-tool.md
Labels: chore

#375 chore: add brew install instructions
  README.md
Labels: chore

#377 fix: .brew_home is created during brew bottling causing git tree state to become dirty
  .gitignore
Labels: fix

#378 chore: use releaseinfo.json to get the latest stable release
  scripts/install.sh
Labels: chore

#379 chore: add kubectl plugins to the install script
  scripts/install.sh
Labels: chore

#380 ci: update index.yaml for helm charts during publish
  .github/workflows/releaseinfo.yml
Labels: ci

#384 ci: fix bug in release workflow and add steps to publish homebrew formula
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: ci

#385 fix: Remove the copysources warning; do not create copysources.sh for UI
  internal/assets/constants.go
  internal/containerizer/scripts/constants.go
  internal/metadata/clusters/constants.go
  internal/move2kube/translator.go
  internal/source/data/constants.go
  internal/transformer/k8stransformer.go
  internal/transformer/knativetransformer.go
  internal/transformer/templates/K8sReadme.md
  internal/transformer/templates/constants.go
  internal/transformer/transformer.go
  internal/types/ir.go
Labels: fix

#386 fix: Correct line spacing between Next Step and first bullet; add new line at end
  internal/assets/constants.go
  internal/containerizer/scripts/constants.go
  internal/metadata/clusters/constants.go
  internal/source/data/constants.go
  internal/transformer/knativetransformer.go
  internal/transformer/templates/K8sReadme.md
  internal/transformer/templates/KnativeReadme.md
  internal/transformer/templates/constants.go
Labels: fix

#387 feat: support multiple k8s resources in a single yaml file
  internal/apiresourceset/k8sapiresourceset.go
  internal/common/utils.go
  internal/metadata/k8sfiles.go
Labels: feat

#388 fix: merge objects using strategic merge patch similar to kustomize and kubectl apply
  internal/apiresource/apiresource.go
  internal/apiresource/apiresource_test.go
  internal/apiresource/deployment.go
  internal/apiresourceset/cicdapiresourceset.go
  internal/apiresourceset/k8sapiresourceset.go
  internal/apiresourceset/knativeapiresourceset.go
  internal/apiresourceset/tektonapiresourceset.go
  internal/common/utils.go
Labels: fix

#389 feat: Initialize only containerizers of interest
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/plan.go
  cmd/move2kube/translate.go
  internal/containerizer/containerizer.go
  internal/move2kube/planner.go
  internal/move2kube/planner_test.go
  internal/move2kube/translator.go
  internal/optimizer/optimizer.go
  internal/source/any2kube.go
  internal/source/any2kube_test.go
  internal/source/cfmanifest2kube.go
  internal/source/translator.go
  types/qaengine/cache.go
Labels: feat

#390 chore: minor refactor
  internal/apiresource/role.go
  internal/collector/cfappscollector.go
  internal/collector/cfcontainertypescollector.go
  internal/containerizer/cnb/containerruntimeprovider.go
  internal/containerizer/cnb/dockerapiprovider.go
  internal/containerizer/cnb/dockerapiprovider_test.go
  internal/containerizer/cnbcontainerizer.go
  internal/containerizer/containerizer.go
  internal/customizer/registrycustomizer.go
  internal/customizer/storagecustomizer.go
  internal/parameterizer/parameterizer_test.go
  internal/transformer/knativetransformer.go
  types/collection/cluster.go
Labels: chore

#392 feat: added segment based containerizer
  internal/containerizer/dockerfilecontainerizer.go
Labels: feat

#399 feat: Add support for converting between kubernetes resource versions
  cmd/move2kube/translate.go
  go.mod
  go.sum
  internal/apiresource/deployment.go
  internal/apiresource/service.go
  internal/apiresourceset/k8sapiresourceset.go
  internal/apiresourceset/k8sfixers.go
  internal/move2kube/planner.go
  internal/transformer/k8stransformer.go
Labels: feat
