Repository konveyor/move2kube, pull requests merged in 2021-03, with the labels that each got.

#441 chore: fix an issue with upx and mac where the process gets killed immediately
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
Labels: chore

#439 feat: add starlark scripting support
  Makefile
  cmd/common/utils.go
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/translate.go
  go.mod
  go.sum
  internal/move2kube/translator.go
  internal/starlark/common/utils.go
  internal/starlark/gettransformdata/gettransformdata.go
  internal/starlark/gettransformdata/simpletransform.go
  internal/starlark/runtransforms/runtransforms.go
  internal/starlark/starlark.go
  internal/starlark/starlark_test.go
  internal/starlark/testdata/k8s-resources/dep-v1.yaml
  internal/starlark/testdata/k8s-resources/dep-v1beta1.yaml
  internal/starlark/testdata/k8s-resources/namespace-v1.yaml
  internal/starlark/testdata/transforms/t1.star
  internal/starlark/testdata/transforms/t2.star
  internal/starlark/testdata/want/demo-namespace.yaml
  internal/starlark/testdata/want/javaspringapp-deployment.yaml
  internal/starlark/testdata/want/nginx-deployment.yaml
  internal/starlark/types/types.go
  internal/transformer/cicdtransformer.go
  internal/transformer/composetransformer.go
  internal/transformer/k8stransformer.go
  internal/transformer/knativetransformer.go
  internal/transformer/transformations/transformations.go
  internal/transformer/transformer.go
Labels: feat

#442 fix: Support extensions group
  go.sum
  internal/k8sschema/converters.go
  types/plan/plan.go
Labels: fix

#443 feat: add version subcommand to translate plugin
  cmd/common/version.go
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/move2kube.go
Labels: feat

#451 fix: javamaven dockerfile template change
  internal/assets/constants.go
  internal/assets/dockerfiles/javamaven/Dockerfile
Labels: fix

#453 fix: image to work with .war files and move2kube-demos
  .gitattributes
  internal/assets/constants.go
  internal/assets/dockerfiles/javamaven/Dockerfile
Labels: fix

#454 chore: build plugin on every release but push to krew only on stable releases
  .github/workflows/release.yml
Labels: chore

#455 fix: add a shebang to make sure script is run with bash
  internal/assets/constants.go
  internal/assets/dockerfiles/django/m2kdfdetect.sh
  internal/assets/dockerfiles/golang/m2kdfdetect.sh
  internal/assets/dockerfiles/java-war-jboss/m2kdfdetect.sh
  internal/assets/dockerfiles/java-war-liberty/m2kdfdetect.sh
  internal/assets/dockerfiles/java-war-tomcat/m2kdfdetect.sh
  internal/assets/dockerfiles/javaant/m2kdfdetect.sh
  internal/assets/dockerfiles/javagradle/m2kdfdetect.sh
  internal/assets/dockerfiles/javamaven/m2kdfdetect.sh
  internal/assets/dockerfiles/nodejs/m2kdfdetect.sh
  internal/assets/dockerfiles/php/m2kdfdetect.sh
  internal/assets/dockerfiles/python/m2kdfdetect.sh
  internal/assets/dockerfiles/ruby/m2kdfdetect.sh
  internal/assets/s2i/golang/m2ks2idetect.sh
  internal/assets/s2i/java/m2ks2idetect.sh
  internal/assets/s2i/nodejs/m2ks2idetect.sh
  internal/assets/s2i/php/m2ks2idetect.sh
  internal/assets/s2i/python/m2ks2idetect.sh
  internal/assets/s2i/ruby/m2ks2idetect.sh
  internal/common/generator/generator.go
  internal/common/generator/generator_test.go
  internal/common/generator/testdata/conststempempty.txt
  internal/common/generator/testdata/conststempfilled.txt
  internal/common/generator/testdata/maptempempty.txt
  internal/common/generator/testdata/maptempfilled.txt
  internal/common/generator/testdata/tartempfilledandtar.txt
  internal/containerizer/dockerfilecontainerizer.go
  internal/containerizer/s2icontainerizer.go
  internal/containerizer/scripts/constants.go
  internal/metadata/clusters/constants.go
  internal/source/data/constants.go
  internal/transformer/templates/constants.go
Labels: fix

#456 chore: update urls to new move2kube.konveyor.io/
  .github/workflows/release.yml
  README.md
  USAGE.md
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/move2kube.go
  releasenotes-config.js
Labels: chore

#460 chore: update the overview image with new logo
  README.md
  imgs/overview.jpg
  imgs/overview.png
Labels: chore
