Repository konveyor/move2kube, pull requests merged in 2021-04, with the labels that each got.

#470 feat: always copy sources to the source folder
  go.mod
  go.sum
  internal/assets/constants.go
  internal/move2kube/translator.go
  internal/transformer/k8stransformer.go
  internal/transformer/knativetransformer.go
  internal/transformer/templates/CopySources.sh
  internal/transformer/templates/K8sReadme.md
  internal/transformer/templates/constants.go
  internal/transformer/transformer.go
  internal/types/ir.go
  scripts/install.sh
Labels: feat

#471 fix: the build in the dockerfile was dirty because some folders were not copied over
  .dockerignore
Labels: fix

#480 fix: helm chart folder name should be same as the chart name
  internal/common/constants.go
  internal/transformer/k8stransformer.go
Labels: fix

#482 fix: Update helm install command with new path
  internal/transformer/templates/DeployHelm.sh
  internal/transformer/templates/constants.go
Labels: fix

#484 fix: the operator was using the wrong helm chart path
  internal/transformer/k8stransformer.go
Labels: fix

#485 feat: generate openshift templates
  go.mod
  internal/assets/constants.go
  internal/common/constants.go
  internal/common/tar.go
  internal/common/utils.go
  internal/starlark/gettransformdata/gettransformdata.go
  internal/starlark/gettransformdata/simpletransform.go
  internal/transformer/k8stransformer.go
  internal/transformer/templates/DeployOCTemplates.sh
  internal/transformer/templates/constants.go
  internal/transformer/transformations/transformations.go
  internal/transformer/transformer.go
Labels: feat

#486 chore: add default answer to the starlark tests
  internal/starlark/testdata/transforms/t1.star
  internal/starlark/testdata/transforms/t2.star
Labels: chore
