Repository konveyor/move2kube, pull requests merged in 2021-09, with the labels that each got.

#585 fix: Naming issues for container block and network policy labels
  internal/apiresource/networkpolicy.go
  internal/apiresource/testdata/networkpolicy/create-new-resources.yaml
  internal/transformer/classes/analysers/compose/v1v2.go
  internal/transformer/classes/analysers/compose/v3.go
Labels: fix

#586 fix: Resolve unable to find ports in Dockerfile bug
  internal/transformer/classes/analysers/dockerfiledetector.go
  internal/transformer/classes/analysers/dockerfileparser.go
Labels: fix

#587 fix: Ignore dirs during iteration in various transformers
  internal/common/constants.go
  internal/common/utils.go
  internal/transformer/classes/analysers/dockerfiledetector.go
  internal/transformer/transformer.go
Labels: fix

#588 fix: Fix service name renaming; Remove error on finding incorrect yamls
  internal/common/constants.go
  internal/common/utils.go
Labels: fix

#578 feat: transformers for windows dotnet 4.x applications
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/winconsole/templates/Dockerfile
  assets/inbuilt/transformers/dockerfile/winconsole/winconsole.yaml
  assets/inbuilt/transformers/dockerfile/winsilverlightweb/templates/Dockerfile
  assets/inbuilt/transformers/dockerfile/winsilverlightweb/winsilverlightweb.yaml
  assets/inbuilt/transformers/dockerfile/winweb/templates/Dockerfile
  assets/inbuilt/transformers/dockerfile/winweb/winweb.yaml
  internal/transformer/classes/generators/dockerfilegenerators/dotnet/consoleappdockerfilegenerator.go
  internal/transformer/classes/generators/dockerfilegenerators/dotnet/silverlightwebappdockerfilegenerator.go
  internal/transformer/classes/generators/dockerfilegenerators/dotnet/utils.go
  internal/transformer/classes/generators/dockerfilegenerators/dotnet/webappdockerfilegenerator.go
  internal/transformer/classes/generators/dockerfilegenerators/utils.go
  internal/transformer/transformer.go
  types/source/dotnet/appconfig.go
  types/source/dotnet/csproj.go
Labels: feat

#590 fix: bug fixes to starlark readdir and template package
  filesystem/templatecopy.go
  internal/transformer/classes/external/starlark.go
Labels: fix

#592 feat: add a REST server to report the progress of the planning phase
  cmd/move2kube/flags.go
  cmd/move2kube/move2kube.go
  cmd/move2kube/plan.go
  cmd/move2kube/utils.go
  cmd/move2kube/validate.go
  internal/common/constants.go
  internal/common/logging.go
  internal/transformer/transformer.go
  lib/validator.go
Labels: feat

#593 feat: log to a file
  cmd/move2kube/move2kube.go
  cmd/move2kube/plan.go
Labels: feat

#595 chore: update readme with new instructions for UI
  README.md
Labels: chore

#597 fix: Fix tab space in Makefile for container runtime check line
  Makefile
Labels: fix
