Repository konveyor/move2kube, pull requests merged in 2021-02, with the labels that each got.

#403 feat: compress binaries
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  scripts/install.sh
Labels: feat

#407 fix: Remove per-service port question
  Makefile
  internal/optimizer/portmergeoptimizer.go
Labels: fix

#408 fix: output path should use the name in the plan file if it exists
  cmd/common/utils.go
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/translate.go
  internal/move2kube/translator.go
Labels: fix

#410 feat: source and output paths should not be parent directories of the current working directory
  cmd/common/utils.go
  cmd/move2kube/translate.go
  internal/common/utils.go
  internal/common/utils_test.go
Labels: feat

#401 feat: Remove support for Kube2Kube and Knative2Kube as services
  go.sum
  internal/apiresource/deployment.go
  internal/apiresourceset/k8sapiresourceset.go
  internal/apiresourceset/knativeapiresourceset.go
  internal/move2kube/planner.go
  internal/qaengine/engine.go
  internal/source/knative2kube.go
  internal/source/kube2kube.go
  internal/source/translator.go
  types/plan/plan.go
Labels: feat

#411 fix: arguments to IsParent were switched
  cmd/common/utils.go
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/translate.go
Labels: fix

#412 fix: stage 2 of select type problem not being asked
  internal/qaengine/cliengine.go
  internal/qaengine/defaultengine.go
  internal/qaengine/engine.go
  internal/qaengine/httprestengine.go
  internal/qaengine/storeengine.go
Labels: fix

#413 chore: octokit is not defined in github workflows, use github instead
  .github/workflows/publish.yml
Labels: chore

#415 feat: support * as a match all selector in qa keys
  internal/common/constants.go
  types/qaengine/config.go
Labels: feat

#416 fix: parsing of config strings
  cmd/kubectltranslate/kubectltranslate.go
  cmd/move2kube/translate.go
  internal/apiresourceset/tektonapiresourceset.go
  internal/common/sshkeys/sshkeys.go
  internal/common/utils.go
  internal/common/utils_test.go
  internal/customizer/storagecustomizer.go
  internal/move2kube/planner.go
  internal/optimizer/ingressoptimizer.go
  internal/qaengine/engine.go
  types/qaengine/config.go
Labels: fix

#418 chore: combine all 3 steps of asking a question into a single function call
  internal/apiresourceset/tektonapiresourceset.go
  internal/common/sshkeys/sshkeys.go
  internal/customizer/ingresscustomizer.go
  internal/customizer/registrycustomizer.go
  internal/customizer/storagecustomizer.go
  internal/move2kube/planner.go
  internal/optimizer/ingressoptimizer.go
  internal/qaengine/defaultengine_test.go
  internal/qaengine/engine.go
  internal/qaengine/storeengine_test.go
Labels: chore

#420 chore: get the new index.yaml from the latest release
  .github/workflows/releaseinfo.yml
Labels: chore

#422 feat: order containerization options in terms of container build type priority
  internal/containerizer/containerizer.go
  internal/containerizer/containerizer_test.go
  internal/move2kube/planner.go
Labels: feat

#424 chore: allow install script to install any tag
  scripts/install.sh
Labels: chore

#429 fix: replace gren with custom action because gren doesn't handle previous tag properly
  .github/workflows/release.yml
  .grenrc.js
Labels: fix

#426 fix: When merging two runtime.Objects, bring them to same version before merging
  internal/apiresource/apiresource.go
  internal/common/utils.go
Labels: fix

#423 feat: Add validate framework to list TODO items after move2kube execution
  cmd/move2kube/move2kube.go
  cmd/move2kube/validate.go
  internal/common/constants.go
  internal/move2kube/validate.go
Labels: feat

#433 fix: Use constructor for buildconfig transformer
  internal/transformer/cicdtransformer.go
Labels: fix

#425 feat: Move container execution logic out of cnb containerizer
  go.sum
  internal/containerexec/dockerengine.go
  internal/containerexec/dockerengine_test.go
  internal/containerexec/engine.go
  internal/containerexec/podmanengine.go
  internal/containerizer/cnb/containerruntimeprovider.go
  internal/containerizer/cnb/packprovider.go
  internal/containerizer/cnb/provider.go
  internal/containerizer/cnb/runcprovider.go
  internal/containerizer/cnbcontainerizer.go
  types/containerizer/containerizer.go
Labels: feat

#434 fix: Reorder versions of the same kind to prioritize k8s versions
  internal/assets/constants.go
  internal/collector/clustercollector.go
  internal/containerizer/scripts/constants.go
  internal/metadata/clusters/constants.go
  internal/metadata/clusters/gcp-gke.yaml
  internal/metadata/clusters/ibm-openshift.yaml
  internal/metadata/clusters/openshift.yaml
  internal/source/data/constants.go
  internal/transformer/templates/constants.go
Labels: fix

#435 chore: Change conversion log messages to debug
  go.mod
  go.sum
  internal/k8sschema/converters.go
Labels: chore

#436 fix: target path should be absolute
  go.mod
  go.sum
  internal/containerizer/dockerfilecontainerizer.go
Labels: fix

#438 chore: Move to go 1.16
  Dockerfile
  go.mod
  go.sum
Labels: chore
