Repository konveyor/move2kube, pull requests merged in 2021-12, with the labels that each got.

#655 ci: add more repos to the release workflow
  .github/workflows/release.yml
Labels: ci

#658 feat: Add support for transformer filtering
  assets/inbuilt/transformers/cloudfoundry/cloudfoundry.yaml
  assets/inbuilt/transformers/compose/composeanalyser/composeanalyser.yaml
  assets/inbuilt/transformers/compose/composegenerator/composegenerator.yaml
  assets/inbuilt/transformers/containerimage/containerimagesbuildscript/containerimagesbuildscript.yaml
  assets/inbuilt/transformers/containerimage/containerimagespushscript/containerimagespushscript.yaml
  assets/inbuilt/transformers/dockerfile/dockerfiledetector/dockerfiledetector.yaml
  assets/inbuilt/transformers/dockerfile/dockerfileparser/dockerfileparser.yaml
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/dockerfilebuildscriptgenerator.yaml
  assets/inbuilt/transformers/dockerfilegenerator/dotnet5/dotnet5.yaml
  assets/inbuilt/transformers/dockerfilegenerator/golang/golang.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/eurekareplaceengine/eureka.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/jar/jar.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/maven/maven.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/zuul/zuulanalyser.yaml
  assets/inbuilt/transformers/dockerfilegenerator/nodejs/nodejs.yaml
  assets/inbuilt/transformers/dockerfilegenerator/php/php.yaml
  assets/inbuilt/transformers/dockerfilegenerator/python/python.yaml
  assets/inbuilt/transformers/dockerfilegenerator/ruby/ruby.yaml
  assets/inbuilt/transformers/dockerfilegenerator/rust/rust.yaml
  assets/inbuilt/transformers/dockerfilegenerator/windows/winconsole/winconsole.yaml
  assets/inbuilt/transformers/dockerfilegenerator/windows/winsilverlightweb/winsilverlightweb.yaml
  assets/inbuilt/transformers/dockerfilegenerator/windows/winweb/winweb.yaml
  assets/inbuilt/transformers/kubernetes/buildconfig/buildconfig.yaml
  assets/inbuilt/transformers/kubernetes/knative/knative.yaml
  assets/inbuilt/transformers/kubernetes/kubernetes/kubernetes.yaml
  assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
  assets/inbuilt/transformers/kubernetes/tekton/tekton.yaml
  assets/inbuilt/transformers/readmegenerator/readmegenerator.yaml
  cmd/move2kube/flags.go
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  common/utils.go
  lib/planner.go
  transformer/cloudfoundrytransformer.go
  transformer/containerizer.go
  transformer/transformer.go
  transformer/utils.go
  types/plan/plan.go
  types/transformer/artifacts/containerizationsconfig.go
Labels: feat

#659 feat: Add support for silent questions which are set only from config
  common/constants.go
  qaengine/engine.go
  transformer/transformer.go
  types/qaengine/problem.go
Labels: feat

#661 feat: Add support for router transformer and war file containerization
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat
  assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/tomcat.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/waranalyser/war.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/warrouter/warrouter.yaml
  lib/planner.go
  qaengine/engine.go
  transformer/containerizer.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/dockerfilegenerator/java/tomcat.go
  transformer/dockerfilegenerator/java/waranalyser.go
  transformer/routertransformer.go
  transformer/transformer.go
  types/qaengine/problem.go
  types/transformer/artifacts/config.go
  types/transformer/artifacts/java.go
  types/transformer/artifacts/newimages.go
Labels: feat

#662 feat: Add war support for liberty and jboss
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/jboss/jboss.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/jboss/templates/Dockerfile.jboss
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/liberty.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/templates/Dockerfile.liberty
  transformer/dockerfilegenerator/java/jboss.go
  transformer/dockerfilegenerator/java/liberty.go
  transformer/routertransformer.go
  transformer/transformer.go
Labels: feat

#665 feat: Make isolation configurable on a per transformer basis
  environment/local.go
  environment/types.go
  transformer/transformer.go
  types/transformer/transformer.go
Labels: feat

#668 ci: point release workflow at the new website repo
  .github/workflows/publish.yml
  .github/workflows/releaseinfo.yml
  scripts/install.sh
Labels: ci

#669 chore: avoid github quota by using Github pages to serve releaseinfo.json
  scripts/install.sh
Labels: chore

#660 feat: Add advanced dotnetcore transformer which supports multiple projects under a solution file
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/dotnet5/dotnet5.yaml
  assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/dotnetcore.yaml
  assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/mappings/dotnetcoreversions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/templates/Dockerfile
  common/constants.go
  transformer/dockerfilegenerator/dotnet5dockerfiletransformer.go
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/windows/utils.go
  transformer/transformer.go
  types/source/dotnet/csproj.go
Labels: feat

#672 fix: Normalize the dotnetcore service name so that it conforms to the Kubernetes standard
  assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/templates/Dockerfile
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
Labels: fix

#673 fix: fix target cluster question not being honored
  apiresource/buildconfig.go
  lib/planner.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/kubernetes/buildconfigtransformer.go
  transformer/kubernetes/tektontransformer.go
Labels: fix

#675 fix: Resolve publish profile path bug
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
Labels: fix

#676 feat: Allow for artifact postprocessing with custom transformers
  transformer/transformer.go
  transformer/utils.go
  types/transformer/transformer.go
Labels: feat

#677 feat: Add support for overriding transformers in custom transformers
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  common/utils.go
  lib/planner.go
  transformer/external/starlarktransformer.go
  transformer/utils.go
  types/transformer/transformer.go
Labels: feat

#679 feat: Allow intercepting artifacts by transformers
  transformer/transformer.go
  types/transformer/transformer.go
Labels: feat

#687 refactor: Move parameterizer to transformer package
  cmd/move2kube/move2kube.go
  cmd/move2kube/parameterize.go
  lib/parameterizer.go
  lib/testdata/parameterizers/pack.yaml
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizer/parameterizer_test.go
  transformer/kubernetes/parameterizer/testdata/k8s-resources/dep-v1.yaml
  transformer/kubernetes/parameterizer/testdata/k8s-resources/dep-v1beta1.yaml
  transformer/kubernetes/parameterizer/testdata/k8s-resources/namespace-v1.yaml
  transformer/kubernetes/parameterizer/testdata/parameterizers/p1.yaml
  transformer/kubernetes/parameterizer/testdata/parameterizers/p2.yaml
  transformer/kubernetes/parameterizer/testdata/want/helm-chart/myproject/Chart.yaml
  transformer/kubernetes/parameterizer/testdata/want/helm-chart/myproject/templates/dep-v1.yaml
  transformer/kubernetes/parameterizer/testdata/want/helm-chart/myproject/templates/dep-v1beta1.yaml
  transformer/kubernetes/parameterizer/testdata/want/helm-chart/myproject/templates/namespace-v1.yaml
  transformer/kubernetes/parameterizer/testdata/want/helm-chart/myproject/values-dev.yaml
  transformer/kubernetes/parameterizer/testdata/want/helm-chart/myproject/values-prod.yaml
  transformer/kubernetes/parameterizer/testdata/want/helm-chart/myproject/values-staging.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/base/dep-v1.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/base/dep-v1beta1.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/base/kustomization.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/base/namespace-v1.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/dev/apps-v1-deployment-nginx.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/dev/extensions-v1beta1-deployment-javaspringapp.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/dev/kustomization.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/prod/apps-v1-deployment-nginx.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/prod/extensions-v1beta1-deployment-javaspringapp.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/prod/kustomization.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/staging/apps-v1-deployment-nginx.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/staging/extensions-v1beta1-deployment-javaspringapp.yaml
  transformer/kubernetes/parameterizer/testdata/want/kustomize/overlays/staging/kustomization.yaml
  transformer/kubernetes/parameterizer/testdata/want/m2kconfig.yaml
  transformer/kubernetes/parameterizer/testdata/want/m2kqacache.yaml
  transformer/kubernetes/parameterizer/testdata/want/openshift-template/parameters-dev.yaml
  transformer/kubernetes/parameterizer/testdata/want/openshift-template/parameters-prod.yaml
  transformer/kubernetes/parameterizer/testdata/want/openshift-template/parameters-staging.yaml
  transformer/kubernetes/parameterizer/testdata/want/openshift-template/template.yaml
  transformer/kubernetes/parameterizer/utils.go
  transformer/kubernetes/parameterizer/utils_test.go
  transformer/kubernetes/parameterizertransformer.go
  types/parameterizer/parameterizer.go
Labels: refactor

#688 fix: Addressed bug in transformer recursion
  transformer/transformer.go
Labels: fix

#689 fix: Added missing shebang in scripts
  assets/inbuilt/transformers/containerimage/containerimagesbuildscript/templates/buildimages.sh
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
Labels: fix

#691 fix: fix cf artifact type setting
  transformer/containerizer.go
Labels: fix

#692 chore: Update dependency versions
  .gitignore
  go.mod
  go.sum
  transformer/kubernetes/kubernetestransformer.go
  transformer/kubernetes/tektontransformer.go
  transformer/transformer.go
Labels: chore

#694 fix: fix random parameterizer test failure
  transformer/kubernetes/parameterizer/testdata/parameterizers/p1.yaml
  transformer/kubernetes/parameterizer/testdata/parameterizers/p2.yaml
Labels: fix

#695 feat: Make parameterizer usable stand alone
  assets/filepermissions.yaml
  assets/inbuilt/transformers/kubernetes/sourceparameterizer/parameterizers.yaml
  transformer/kubernetes/k8sschema/k8sschema.go
  transformer/kubernetes/k8sschema/utils.go
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizer/parameterizer_test.go
  transformer/kubernetes/parameterizer/types.go
  transformer/kubernetes/parameterizer/utils.go
  transformer/kubernetes/parameterizertransformer.go
  types/output/helmvaluesoutput.go
  types/output/helmvaluesoutput_test.go
Labels: feat

#696 fix: Prevent SourceParameterizer from being triggered for new apps
  assets/inbuilt/transformers/kubernetes/sourceparameterizer/parameterizers.yaml
Labels: fix

#693 feat: Add netcoreapp3.1 and net6.0 to the supported dotnetcore frameworks
  assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/dotnetcore.yaml
  assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/mappings/dotnetcoreversions.yaml
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
Labels: feat

#697 feat: Add support for kubernetes resource version transformation
  assets/filepermissions.yaml
  assets/inbuilt/transformers/kubernetes/clusterselector/clusterselector.yaml
  assets/inbuilt/transformers/kubernetes/kubernetesversionchanger/kubernetesversionchanger.yaml
  assets/inbuilt/transformers/kubernetes/parameterizer/parameterizer.yaml
  assets/inbuilt/transformers/kubernetes/parameterizers/parameterizers.yaml
  assets/inbuilt/transformers/kubernetes/sourceparameterizer/parameterizers.yaml
  common/constants.go
  environment/environment.go
  lib/planner.go
  transformer/kubernetes/apiresource/apiresource.go
  transformer/kubernetes/apiresource/utils.go
  transformer/kubernetes/buildconfigtransformer.go
  transformer/kubernetes/k8sschema/utils.go
  transformer/kubernetes/knativetransformer.go
  transformer/kubernetes/kubernetestransformer.go
  transformer/kubernetes/kubernetesversionchangertransformer.go
  transformer/kubernetes/parameterizertransformer.go
  transformer/kubernetes/tektontransformer.go
  transformer/transformer.go
  transformer/utils.go
  types/transformer/artifacts/kubernetes.go
Labels: feat

#698 fix: Use go install in Makefile since go get is deprecated for binary installs
  Makefile
  transformer/dockerfilegenerator/java/gradle/gradleparser.go
  transformer/utils.go
Labels: fix

#699 feat: Add support for in-built cloud specific cluster versions
  assets/filepermissions.yaml
  assets/inbuilt/transformers/kubernetes/clusterselector/clusters/aws-eks.yaml
  assets/inbuilt/transformers/kubernetes/clusterselector/clusters/azure-aks.yaml
  assets/inbuilt/transformers/kubernetes/clusterselector/clusters/gcp-gke.yaml
  assets/inbuilt/transformers/kubernetes/clusterselector/clusters/ibm-iks.yaml
  assets/inbuilt/transformers/kubernetes/clusterselector/clusters/ibm-openshift.yaml
Labels: feat

#700 feat: Add support for podman in scripts
  README.md
  assets/filepermissions.yaml
  assets/inbuilt/transformers/containerimage/containerimagesbuildscript/containerimagesbuildscript.yaml
  assets/inbuilt/transformers/containerimage/containerimagesbuildscript/templates/buildimages.bat
  assets/inbuilt/transformers/containerimage/containerimagesbuildscript/templates/buildimages.sh
  assets/inbuilt/transformers/containerimage/containerimagespushscript/templates/pushimages.bat
  assets/inbuilt/transformers/containerimage/containerimagespushscript/templates/pushimages.sh
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
  common/constants.go
  transformer/containerimage/containerimagesbuildscripttransformer.go
  transformer/containerimage/containerimagespushscripttransformer.go
  transformer/dockerfile/dockerfilebuildscripttransformer.go
  transformer/transformer.go
  types/qaengine/commonqa/commonqa.go
  types/transformer/artifacts/containerimagesbuildscript.go
Labels: feat

#701 feat: Add support for zuul processor for IR
  assets/inbuilt/transformers/dockerfilegenerator/java/zuul/zuulanalyser.yaml
  transformer/dockerfilegenerator/java/zuulanalyser.go
Labels: feat
