Repository konveyor/move2kube, pull requests merged in 2021-07, with the labels that each got.

#534 feat: Process all source mappings before other mapping types to prevent overwrite
  assets/inbuilt/transformers/executable/dockerfile/golang/golang.yaml
  filesystem/merger.go
  internal/transformer/processors.go
Labels: feat

#535 feat: Add support for image push scripts and common qa set
  assets/filepermissions.yaml
  assets/inbuilt/transformers/compose/composeanalyser/composeanalyser.yaml
  assets/inbuilt/transformers/compose/composegenerator/composegenerator.yaml
  assets/inbuilt/transformers/scriptsgenerator/containerpushscripts/templates/pushimages.bat
  filesystem/templatecopy.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/generators/cnbgenerator.go
  internal/transformer/classes/metaartifacts/containerimagepushscript.go
  types/qaengine/commonqa/commonqa.go
Labels: feat

#519 feat: Add Containerizer plugin for Rust
  assets/inbuilt/transformers/executable/dockerfile/rust/m2kdetect.sh
  assets/inbuilt/transformers/executable/dockerfile/rust/rust.yaml
  assets/inbuilt/transformers/executable/dockerfile/rust/templates/Dockerfile
  samples/rust/Cargo.toml
  samples/rust/src/main.rs
Labels: feat

#536 feat: Add default ignore list for directory names
  assets/filepermissions.yaml
  internal/transformer/transformer.go
Labels: feat

#533 feat: Native Support for Netflix OSS transformation
  assets/filepermissions.yaml
  assets/inbuilt/transformers/springboot/eurekareplaceengine/eureka.yaml
  assets/inbuilt/transformers/springboot/java-springboot/java-springboot.yaml
  assets/inbuilt/transformers/springboot/java-springboot/templates/Dockerfile.license
  assets/inbuilt/transformers/springboot/java-springboot/templates/Dockerfile.maven-build
  assets/inbuilt/transformers/springboot/java-springboot/templates/Dockerfile.springboot-embedded
  assets/inbuilt/transformers/springboot/zuul/zuulanalyser.yaml
  go.mod
  go.sum
  internal/transformer/classes/analysers/eurekareplaceengine.go
  internal/transformer/classes/analysers/springbootanalyser.go
  internal/transformer/classes/analysers/zuulanalyser.go
  internal/transformer/transformer.go
  types/source/maven/pom.go
Labels: feat

#537 fix: Fix and cleanup eureka and springboot transforms
  internal/transformer/classes/analysers/eurekareplaceengine.go
  internal/transformer/classes/analysers/springbootanalyser.go
Labels: fix

#538 refactor: minor changes to code style
  internal/transformer/classes/analysers/eurekareplaceengine.go
  internal/transformer/classes/analysers/springbootanalyser.go
  internal/transformer/classes/generators/buildconfiggenerator.go
  internal/transformer/classes/generators/composegenerator.go
  internal/transformer/classes/generators/knativegenerator.go
  internal/transformer/classes/generators/kubernetesgenerator.go
  internal/transformer/classes/generators/tektongenerator.go
  internal/transformer/processors.go
  internal/transformer/servicenamer.go
  internal/transformer/transformer.go
  internal/transformer/utils.go
  types/ir/ir.go
  types/plan/plan.go
  types/source/maven/pom.go
Labels: refactor

#541 feat: Add support for read access to filesystem for starlark transformers
  api/planner.go
  assets/filepermissions.yaml
  assets/inbuilt/transformers/cloudfoundry/cloudfoundry.yaml
  assets/inbuilt/transformers/cnb/cfcnb/cfcnb.yaml
  assets/inbuilt/transformers/cnb/gcrcnb/gcrcnb.yaml
  assets/inbuilt/transformers/compose/composeanalyser/composeanalyser.yaml
  assets/inbuilt/transformers/dockerfile/django/django.yaml
  assets/inbuilt/transformers/dockerfile/golang/golang.yaml
  assets/inbuilt/transformers/dockerfile/java-war-jboss/java-war-jboss.yaml
  assets/inbuilt/transformers/dockerfile/java-war-liberty/java-war-liberty.yaml
  assets/inbuilt/transformers/dockerfile/java-war-tomcat/java-war-tomcat.yaml
  assets/inbuilt/transformers/dockerfile/javaant/javaant.yaml
  assets/inbuilt/transformers/dockerfile/javagradle/javagradle.yaml
  assets/inbuilt/transformers/dockerfile/javamaven/javamaven.yaml
  assets/inbuilt/transformers/dockerfile/nodejs/nodejs.yaml
  assets/inbuilt/transformers/dockerfile/php/php.yaml
  assets/inbuilt/transformers/dockerfile/python/python.yaml
  assets/inbuilt/transformers/dockerfile/ruby/ruby.yaml
  assets/inbuilt/transformers/dockerfile/rust/rust.yaml
  assets/inbuilt/transformers/dockerfiledetector/dockerfiledetector.yaml
  assets/inbuilt/transformers/s2i/golang/golang.yaml
  assets/inbuilt/transformers/s2i/java/java.yaml
  assets/inbuilt/transformers/s2i/nodejs/m2kdetect.sh
  assets/inbuilt/transformers/s2i/nodejs/nodejs.star
  assets/inbuilt/transformers/s2i/nodejs/nodejs.yaml
  assets/inbuilt/transformers/s2i/php/php.yaml
  assets/inbuilt/transformers/s2i/python/python.yaml
  assets/inbuilt/transformers/s2i/ruby/ruby.yaml
  assets/inbuilt/transformers/springboot/java-springboot/java-springboot.yaml
  environment/local.go
  go.mod
  internal/transformer/classes/analysers/cloudfoundryanalyser.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/analysers/composeanalyser.go
  internal/transformer/classes/analysers/dockerfileanalyser.go
  internal/transformer/classes/analysers/eurekareplaceengine.go
  internal/transformer/classes/analysers/springbootanalyser.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/classes/external/starlark.go
  internal/transformer/classes/generators/s2igenerator.go
  types/plan/plan.go
  types/transformer/artifact.go
  types/transformer/transformer.go
Labels: feat

#542 feat: Added support for existing dockerfile detector
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/dockerfiledetector/dockerfiledetector.yaml
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/docckerfilebuildscriptgenerator.yaml
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
  assets/inbuilt/transformers/s2i/nodejs/nodejs.star
  environment/environment.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/analysers/dockerfileanalyser.go
  internal/transformer/classes/external/starlark.go
  internal/transformer/classes/generators/containerimagepushscript.go
  internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
  internal/transformer/classes/generators/readmegenerator.go
  internal/transformer/classes/generators/s2igenerator.go
  internal/transformer/transformer.go
  types/transformer/artifacts/dockerimagebuildscript.go
Labels: feat

#544 feat: Use names of known services to guess names of unknown services using project paths
  internal/transformer/servicenamer.go
  types/source/maven/pom.go
Labels: feat

#545 feat: Add support for references to output files in artifacts
  api/planner.go
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  environment/environment.go
  environment/local.go
  environment/peercontainer.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
  internal/transformer/transformer.go
Labels: feat

#546 feat: Add support for build scripts and readme
  assets/filepermissions.yaml
  assets/inbuilt/transformers/cnb/cnbgenerator/templates/cnbbuild.bat
  assets/inbuilt/transformers/cnb/cnbgenerator/templates/cnbbuild.sh
  assets/inbuilt/transformers/generators/containerimagesbuildscript/containerimagesbuildscript.yaml
  assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.bat
  assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.sh
  assets/inbuilt/transformers/generators/containerimagespushscript/containerimagespushscript.yaml
  assets/inbuilt/transformers/generators/containerimagespushscript/templates/pushimages.bat
  assets/inbuilt/transformers/generators/containerimagespushscript/templates/pushimages.sh
  assets/inbuilt/transformers/generators/readmegenerator/readmegenerator.yaml
  assets/inbuilt/transformers/generators/readmegenerator/templates/Readme.md
  assets/inbuilt/transformers/s2i/buildscriptgenerator/templates/s2ibuild.bat
  assets/inbuilt/transformers/s2i/buildscriptgenerator/templates/s2ibuild.sh
  environment/environment.go
  internal/transformer/classes/analysers/cloudfoundryanalyser.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/analysers/composeanalyser.go
  internal/transformer/classes/analysers/dockerfileanalyser.go
  internal/transformer/classes/analysers/eurekareplaceengine.go
  internal/transformer/classes/analysers/springbootanalyser.go
  internal/transformer/classes/analysers/zuulanalyser.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/classes/external/starlark.go
  internal/transformer/classes/generators/buildconfiggenerator.go
  internal/transformer/classes/generators/cnbgenerator.go
  internal/transformer/classes/generators/composegenerator.go
  internal/transformer/classes/generators/containerimagesbuildscript.go
  internal/transformer/classes/generators/containerimagespushscript.go
  internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
  internal/transformer/classes/generators/knativegenerator.go
  internal/transformer/classes/generators/kubernetesgenerator.go
  internal/transformer/classes/generators/readmegenerator.go
  internal/transformer/classes/generators/s2igenerator.go
  internal/transformer/classes/generators/tektongenerator.go
  internal/transformer/transformer.go
  types/source/maven/pom.go
  types/transformer/artifacts/containerimagebuildscript.go
  types/transformer/artifacts/containerimagesbuildscript.go
  types/transformer/artifacts/containerimagespushscript.go
Labels: feat

#547 fix: Make only lower case container image names
  internal/common/utils.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/analysers/dockerfileanalyser.go
  internal/transformer/classes/generators/cnbgenerator.go
  internal/transformer/classes/generators/s2igenerator.go
Labels: fix

#548 fix: Merge artifacts of same type before usage
  assets/inbuilt/transformers/generators/containerimagespushscript/containerimagespushscript.yaml
  assets/inbuilt/transformers/generators/readmegenerator/readmegenerator.yaml
  internal/common/deepcopy/merge.go
  internal/transformer/classes/analysers/dockerfileanalyser.go
  internal/transformer/classes/generators/cnbgenerator.go
  internal/transformer/classes/generators/containerimagespushscript.go
  internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
  internal/transformer/classes/generators/s2igenerator.go
  types/transformer/artifact.go
  types/transformer/artifacts/newimages.go
Labels: fix

#550 feat: Add support for dockerfile analysis, autofilling of IR, and golang based dockerfile transformers
  api/planner.go
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/dockerfileparser/dockerfileparser.yaml
  assets/inbuilt/transformers/dockerfile/nodejs/m2kdetect.sh
  assets/inbuilt/transformers/dockerfile/nodejs/nodejs.yaml
  assets/inbuilt/transformers/dockerfile/nodejs/templates/Dockerfile
  environment/environment.go
  go.mod
  go.sum
  internal/transformer/classes/analysers/cloudfoundryanalyser.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/analysers/composeanalyser.go
  internal/transformer/classes/analysers/dockerfiledetector.go
  internal/transformer/classes/analysers/dockerfileparser.go
  internal/transformer/classes/analysers/eurekareplaceengine.go
  internal/transformer/classes/analysers/springbootanalyser.go
  internal/transformer/classes/analysers/zuulanalyser.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/classes/generators/buildconfiggenerator.go
  internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
  internal/transformer/classes/generators/dockerfilegenerators/nodejsdockerfilegenerator.go
  internal/transformer/classes/generators/dockerfilegenerators/utils.go
  internal/transformer/classes/generators/knativegenerator.go
  internal/transformer/classes/generators/kubernetesgenerator.go
  internal/transformer/classes/generators/s2igenerator.go
  internal/transformer/classes/generators/tektongenerator.go
  internal/transformer/transformer.go
  internal/transformer/utils.go
  types/transformer/artifacts/dockerfileartifact.go
  types/transformer/artifacts/dockerfileforservice.go
Labels: feat

#551 feat: Add IR preprocessors and allow configuration of qa cache and config files
  cmd/common/utils.go
  cmd/move2kube/transform.go
  internal/irpreprocessor/ingresspreprocessor.go
  internal/transformer/classes/generators/kubernetesgenerator.go
Labels: feat

#552 refactor: Change configurations flag to customizations to avoid confusion with config
  api/planner.go
  cmd/common/utils.go
  cmd/move2kube/parameterize.go
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  internal/common/utils.go
  types/plan/plan.go
Labels: refactor

#553 feat: Add support for windows and ARM
  Makefile
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
  assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.bat
  assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.sh
  internal/transformer/classes/generators/containerimagesbuildscript.go
  internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
Labels: feat

#555 chore: Cleanup vestigial artifacts
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  Dockerfile
  README.md
  assets/inbuilt/presets/dc.yaml
  cmd/move2kube/collect.go
  cmd/move2kube/parameterize.go
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  cmd/move2kube/validate.go
  cmd/move2kube/version.go
  containerconfig/containers.conf
  containerconfig/storage.conf
  docs/README.md
  docs/docker-containerization.md
  imgs/e2e-flow.svg
  imgs/usage.png
  lib/collector.go
  lib/parameterizer.go
  lib/parameterizer_test.go
  lib/planner.go
  lib/testdata/k8s-resources/dep-v1.yaml
  lib/testdata/k8s-resources/dep-v1beta1.yaml
  lib/testdata/k8s-resources/namespace-v1.yaml
  lib/testdata/parameterizers/p1.yaml
  lib/testdata/parameterizers/p2.yaml
  lib/testdata/parameterizers/pack.yaml
  lib/testdata/want/helm-chart/myproject/Chart.yaml
  lib/testdata/want/helm-chart/myproject/templates/dep-v1.yaml
  lib/testdata/want/helm-chart/myproject/templates/dep-v1beta1.yaml
  lib/testdata/want/helm-chart/myproject/templates/namespace-v1.yaml
  lib/testdata/want/helm-chart/myproject/values-dev.yaml
  lib/testdata/want/helm-chart/myproject/values-prod.yaml
  lib/testdata/want/helm-chart/myproject/values-staging.yaml
  lib/testdata/want/kustomize/base/dep-v1.yaml
  lib/testdata/want/kustomize/base/dep-v1beta1.yaml
  lib/testdata/want/kustomize/base/kustomization.yaml
  lib/testdata/want/kustomize/base/namespace-v1.yaml
  lib/testdata/want/kustomize/overlays/dev/apps-v1-deployment-nginx.yaml
  lib/testdata/want/kustomize/overlays/dev/extensions-v1beta1-deployment-javaspringapp.yaml
  lib/testdata/want/kustomize/overlays/dev/kustomization.yaml
  lib/testdata/want/kustomize/overlays/prod/apps-v1-deployment-nginx.yaml
  lib/testdata/want/kustomize/overlays/prod/extensions-v1beta1-deployment-javaspringapp.yaml
  lib/testdata/want/kustomize/overlays/prod/kustomization.yaml
  lib/testdata/want/kustomize/overlays/staging/apps-v1-deployment-nginx.yaml
  lib/testdata/want/kustomize/overlays/staging/extensions-v1beta1-deployment-javaspringapp.yaml
  lib/testdata/want/kustomize/overlays/staging/kustomization.yaml
  lib/testdata/want/m2kconfig.yaml
  lib/testdata/want/m2kqacache.yaml
  lib/testdata/want/openshift-template/parameters-dev.yaml
  lib/testdata/want/openshift-template/parameters-prod.yaml
  lib/testdata/want/openshift-template/parameters-staging.yaml
  lib/testdata/want/openshift-template/template.yaml
  lib/transformer.go
  lib/validator.go
  lib/version.go
  qaengine/engine.go
Labels: chore

#557 feat: Add windows support
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/django/django.yaml
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
  assets/inbuilt/transformers/dockerfile/golang/golang.yaml
  assets/inbuilt/transformers/dockerfile/java-war-jboss/java-war-jboss.yaml
  assets/inbuilt/transformers/dockerfile/java-war-liberty/java-war-liberty.yaml
  assets/inbuilt/transformers/dockerfile/java-war-tomcat/java-war-tomcat.yaml
  assets/inbuilt/transformers/dockerfile/javaant/javaant.yaml
  assets/inbuilt/transformers/dockerfile/javagradle/javagradle.yaml
  assets/inbuilt/transformers/dockerfile/javamaven/javamaven.yaml
  assets/inbuilt/transformers/dockerfile/php/php.yaml
  assets/inbuilt/transformers/dockerfile/python/python.yaml
  assets/inbuilt/transformers/dockerfile/ruby/ruby.yaml
  assets/inbuilt/transformers/dockerfile/rust/rust.yaml
  assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.bat
  assets/inbuilt/transformers/s2i/golang/golang.yaml
  assets/inbuilt/transformers/s2i/java/java.yaml
  assets/inbuilt/transformers/s2i/php/php.yaml
  assets/inbuilt/transformers/s2i/python/python.yaml
  assets/inbuilt/transformers/s2i/ruby/ruby.yaml
  internal/common/utils.go
  internal/transformer/classes/analysers/dockerfiledetector.go
  internal/transformer/classes/external/simpleexecutable.go
  internal/transformer/classes/external/starlark.go
  internal/transformer/classes/external/types.go
  types/transformer/transformer.go
Labels: feat

#559 feat: Add support for windows containers
  internal/apiresource/service.go
  internal/common/constants.go
  internal/irpreprocessor/irpreprocessor.go
  internal/irpreprocessor/mergepreprocessor.go
  internal/irpreprocessor/registrypreprocessor.go
  internal/transformer/classes/analysers/dockerfileparser.go
  types/qaengine/commonqa/commonqa.go
Labels: feat

#560 fix: Fix ports and remove service to ingress
  internal/apiresource/buildconfig.go
  internal/apiresource/service.go
  internal/common/constants.go
  internal/irpreprocessor/ingresspreprocessor.go
  internal/irpreprocessor/mergepreprocessor.go
  internal/irpreprocessor/registrypreprocessor.go
  internal/irpreprocessor/replicapreprocessor.go
  internal/irpreprocessor/replicapreprocessor_test.go
  internal/transformer/classes/analysers/dockerfileparser.go
  internal/transformer/classes/generators/tektongenerator.go
  types/ir/ir.go
  types/qaengine/commonqa/commonqa.go
  types/qaengine/config.go
Labels: fix

#565 fix: Fix build script context paths
  assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.bat
  assets/inbuilt/transformers/generators/containerimagesbuildscript/templates/buildimages.sh
  internal/transformer/classes/generators/containerimagesbuildscript.go
  internal/transformer/classes/generators/dockerfilebuildscriptgenerator.go
  types/transformer/artifacts/containerimagebuildscript.go
Labels: fix

#566 feat: Change logging to support multiple levels; cleanup on interrupt
  cmd/move2kube/move2kube.go
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  environment/environment.go
  environment/error.go
  environment/local.go
  environment/peercontainer.go
  internal/common/logging.go
  internal/common/utils.go
  internal/transformer/classes/analysers/cnbcontainerizer.go
  internal/transformer/classes/external/executable.go
  lib/planner.go
  lib/transformer.go
Labels: feat

#568 fix: Fix conflicting flags and missing cleanup at end of execution
  cmd/move2kube/move2kube.go
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
Labels: fix

#569 chore: Remove the golang sample
  samples/golang/main.go
Labels: chore

#556 feat: parameter extraction and image selection
  assets/filepermissions.yaml
  assets/inbuilt/transformers/springboot/java-springboot/mappings/java2images_tags.yaml
  assets/inbuilt/transformers/springboot/java-springboot/mappings/java_version2package_name.json
  assets/inbuilt/transformers/springboot/java-springboot/templates/Dockerfile.maven-build
  assets/inbuilt/transformers/springboot/java-springboot/templates/Dockerfile.springboot-embedded
  assets/inbuilt/transformers/springboot/java-springboot/templates/Dockerfile.springboot-open-liberty-runtime
  assets/inbuilt/transformers/springboot/java-springboot/templates/Dockerfile.springboot-wildfly-jboss-runtime
  internal/transformer/classes/analysers/springbootanalyser.go
  types/collection/image.go
Labels: feat

#571 fix: Resolve the windows nodeselector bug
  internal/transformer/classes/analysers/dockerfileparser.go
Labels: fix

#570 feat: Replace shell script based transformer for detecting golang with golang based transformer
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/golang/Dockerfile
  assets/inbuilt/transformers/dockerfile/golang/golang.yaml
  assets/inbuilt/transformers/dockerfile/golang/m2kdetect.sh
  assets/inbuilt/transformers/dockerfile/golang/templates/Dockerfile
  go.mod
  go.sum
  internal/common/constants.go
  internal/transformer/classes/generators/dockerfilegenerators/golangdockerfilegenerator.go
  internal/transformer/transformer.go
  types/qaengine/commonqa/commonqa.go
Labels: feat
