Repository konveyor/move2kube, pull requests merged in 2021-08, with the labels that each got.

#575 feat: Add golang-based transformer for PHP
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/php/m2kdetect.sh
  assets/inbuilt/transformers/dockerfile/php/php.yaml
  assets/inbuilt/transformers/dockerfile/php/templates/Dockerfile
  go.mod
  go.sum
  internal/common/constants.go
  internal/transformer/classes/generators/dockerfilegenerators/phpdockerfilegenerator.go
  internal/transformer/transformer.go
  samples/php/index.php
  samples/php/site.conf
  types/qaengine/commonqa/commonqa.go
Labels: feat

#577 feat: Extract node version, build and port information in Nodejs transformer; Fix deployment yaml bug.
  assets/inbuilt/transformers/dockerfile/nodejs/nodejs.yaml
  assets/inbuilt/transformers/dockerfile/nodejs/templates/Dockerfile
  environment/container/container.go
  go.mod
  go.sum
  internal/common/constants.go
  internal/irpreprocessor/mergepreprocessor.go
  internal/transformer/classes/generators/dockerfilegenerators/nodejsdockerfilegenerator.go
Labels: feat

#580 fix: Target windows node if the dockerfile template is windows platform based
  internal/transformer/classes/analysers/dockerfileparser.go
Labels: fix

#581 chore: Update go version to 1.17; update dependencies
  Dockerfile
  Makefile
  README.md
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfile/golang/golang.yaml
  assets/inbuilt/transformers/generators/parameterizers/parameterizers.yaml
  cmd/move2kube/move2kube.go
  cmd/move2kube/version.go
  go.mod
  go.sum
  types/qaengine/config.go
Labels: chore

#582 feat: Automatically add path if path is missing in external transformer class
  internal/transformer/classes/external/executable.go
  internal/transformer/transformer.go
  internal/transformer/utils.go
  lib/planner.go
  types/transformer/plan.go
Labels: feat
