Repository konveyor/move2kube, pull requests merged in 2022-07, with the labels that each got.

#821 fix: the run stage of dockerfiles generated for dot net web app was using a deprecated base image
  assets/built-in/transformers/dockerfilegenerator/windows/mappings/dotnetwindowsversionmapping.yaml
  assets/built-in/transformers/dockerfilegenerator/windows/winweb/templates/Dockerfile
  assets/built-in/transformers/dockerfilegenerator/windows/winweb/transformer.yaml
  assets/filepermissions.yaml
  common/utils.go
  filesystem/templatecopy.go
  transformer/dockerfilegenerator/windows/types.go
  transformer/dockerfilegenerator/windows/utils.go
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
Labels: fix

#822 fix: IngressClassName missing #790
  common/constants.go
  transformer/kubernetes/apiresource/service.go
Labels: fix

#815 feat: User-defined label for cluster related QA
  common/constants.go
  transformer/kubernetes/apiresource/service.go
  transformer/kubernetes/clusterselector.go
  types/collection/cluster.go
  types/qaengine/commonqa/commonqa.go
Labels: feat

#823 fix: panic when docker is not installed and CNB containerizer is used
  environment/container/container.go
  environment/container/dockerengine.go
  environment/container/dockerengine_test.go
Labels: fix

#826 fix: Qalabel label patch
  common/constants.go
  transformer/kubernetes/apiresource/service.go
  transformer/kubernetes/clusterselector.go
  types/collection/cluster.go
  types/qaengine/commonqa/commonqa.go
Labels: fix

#827 refactor: support only docker for multi arch image build
  Makefile
Labels: refactor

#829 fix: the default cluster name so that QA works properly
  transformer/kubernetes/clusterselector.go
Labels: fix

#828 fix: multi arch build with buildkit always enabled
  .github/workflows/release.yml
  Dockerfile
Labels: fix

#830 fix: workflow uses multi arch build and push, cache from latest, handle platform args
  .github/workflows/release.yml
  Dockerfile
  Makefile
Labels: fix

#831 fix: setup qemu and buildx to worlflows
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: fix

#832 fix: panic when target framework version is not present in a dot net c sharp project file
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/utils.go
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
Labels: fix

#833 fix: identifier issue in workflow
  .github/workflows/build.yml
Labels: fix

#838 fix: ir was not being propagated through artifacts for use by downstream transformers
  transformer/dockerfilegenerator/java/jaranalyser.go
Labels: fix

#834 feat: Add node version selection heuristic to handle conditional Node.JS version in package.json
  assets/built-in/transformers/dockerfilegenerator/mappings/nodeversions.yaml
  assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
  assets/built-in/transformers/dockerfilegenerator/nodejs/transformer.yaml
  assets/filepermissions.yaml
  go.mod
  go.sum
  samples/nodejs/package.json
  transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
  transformer/dockerfilegenerator/utils.go
Labels: feat

#840 fix: detect the node version from the package.json in the dot net core transformer instead of hard coding
  assets/built-in/transformers/dockerfilegenerator/dotnetcore/templates/Dockerfile
  assets/built-in/transformers/dockerfilegenerator/dotnetcore/transformer.yaml
  assets/built-in/transformers/dockerfilegenerator/mappings/nodeversions.yaml
  assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
  common/utils.go
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
  transformer/routertransformer.go
Labels: fix

#841 chore: capitalize the start of a sentence in a question.
  transformer/dockerfilegenerator/java/mavenanalyser.go
Labels: chore
