Repository konveyor/move2kube, pull requests merged in 2022-01, with the labels that each got.

#702 fix: remove old version of eureka refactor engine
  transformer/dockerfilegenerator/java/eurekareplaceengine.go
  transformer/transformer.go
Labels: fix

#703 feat: Check and remove paths outside move2kube relevant folders in artifacts and pathmappings
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/eurekareplaceengine/eureka.yaml
  environment/environment.go
Labels: feat

#704 feat: Restrict starlark file access to only move2kube relevant folders
  environment/environment.go
  transformer/external/starlarktransformer.go
Labels: feat

#705 feat: Add flag to allow for disabling local file execution
  cmd/move2kube/plan.go
  cmd/move2kube/transform.go
  cmd/move2kube/version.go
  common/constants.go
  environment/local.go
Labels: feat

#707 docs: expose all the commands to help generate docs externally
  Makefile
  cmd/commands/collect.go
  cmd/commands/docs.go
  cmd/commands/flags.go
  cmd/commands/plan.go
  cmd/commands/root.go
  cmd/commands/transform.go
  cmd/commands/umask.go
  cmd/commands/utils.go
  cmd/commands/version.go
  cmd/main.go
  go.mod
  go.sum
Labels: docs

#708 fix: relative links break when building on github even though they work when building locally
  cmd/commands/docs.go
Labels: fix

#709 fix: Remove space from cluster name in move2kube collect
  collector/clustercollector.go
Labels: fix

#710 feat: Add a preset to use podman in generated scripts
  assets/filepermissions.yaml
  assets/inbuilt/presets/dc.yaml
  assets/inbuilt/presets/usepodmaninscripts.yaml
Labels: feat

#711 feat: check the directory the script is being run from and give a warning
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
Labels: feat

#712 feat: Rename projectpath as servicedirpath and rename rootdir in plan as sourcedir
  assets/inbuilt/transformers/dockerfilegenerator/python/templates/Dockerfile
  cmd/commands/transform.go
  lib/planner.go
  transformer/cloudfoundrytransformer.go
  transformer/compose/composeanalyser.go
  transformer/dockerfile/dockerfiledetectortransformer.go
  transformer/dockerfile/dockerfileparsertransformer.go
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/golangdockerfiletransformer.go
  transformer/dockerfilegenerator/java/earanalyser.go
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/jaranalyser.go
  transformer/dockerfilegenerator/java/jboss.go
  transformer/dockerfilegenerator/java/liberty.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/dockerfilegenerator/java/tomcat.go
  transformer/dockerfilegenerator/java/waranalyser.go
  transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
  transformer/dockerfilegenerator/phpdockerfiletransformer.go
  transformer/dockerfilegenerator/pythondockerfiletransformer.go
  transformer/dockerfilegenerator/rubydockerfiletransformer.go
  transformer/dockerfilegenerator/rustdockerfiletransformer.go
  transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/utils.go
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
  transformer/external/executabletransformer.go
  transformer/kubernetes/kubernetestransformer.go
  transformer/kubernetes/kubernetesversionchangertransformer.go
  transformer/kubernetes/parameterizertransformer.go
  transformer/servicenamer.go
  transformer/transformer.go
  types/plan/plan.go
  types/plan/planutils.go
  types/plan/testdata/setrootdir/nodejsplan.yaml
  types/plan/testdata/setrootdir/templatizednodejsplan.yaml
  types/plan/testdata/writeplan/nodejsplan.yaml
  types/transformer/artifacts/artifacts.go
Labels: feat

#713 feat: Use transformerName to denote processing transformer for each service in plan
  lib/planner.go
  transformer/cloudfoundrytransformer.go
  transformer/compose/composeanalyser.go
  transformer/containerizer.go
  transformer/servicenamer.go
  transformer/transformer.go
  transformer/utils.go
  types/plan/plan.go
Labels: feat

#714 feat: Add replicas parameterization as default parameterization
  assets/filepermissions.yaml
  assets/inbuilt/transformers/kubernetes/parameterizer/config/replicas.yaml
Labels: feat

#715 chore: remove reference to personal repos/forks
  .github/workflows/release.yml
Labels: chore

#716 chore: remove personal names and references
  transformer/kubernetes/apiresource/buildconfig.go
Labels: chore

#717 fix: Fix support for containerization in cloud foundry
  transformer/containerizer.go
Labels: fix

#706 fix: Format the interfaces in map values as json
  collector/cfappscollector.go
  transformer/cloudfoundrytransformer.go
  types/collection/cfapps.go
Labels: fix

#718 fix: fix usage of docker image in cloud foundry
  transformer/cloudfoundrytransformer.go
Labels: fix

#719 fix: bug where 2 questions about port are asked
  assets/inbuilt/transformers/dockerfilegenerator/java/earrouter/earrouter.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/warrouter/warrouter.yaml
Labels: fix

#671 feat: Flatten vcap variables
  common/utils.go
  filesystem/templatecopy.go
  go.mod
  go.sum
  transformer/cloudfoundrytransformer.go
Labels: feat

#721 feat: Add support for building dockerfile in compose
  assets/inbuilt/transformers/compose/composeanalyser/composeanalyser.yaml
  transformer/compose/composeanalyser.go
  transformer/compose/v1v2.go
  transformer/compose/v3.go
  transformer/dockerfile/dockerfilebuildscripttransformer.go
  transformer/kubernetes/apiresource/pipeline.go
  types/ir/ir.go
  types/transformer/artifacts/dockerfileartifact.go
Labels: feat

#720 fix: Update readme to state that in some situations scripts directory might be missing
  assets/inbuilt/transformers/readmegenerator/templates/Readme.md
Labels: fix

#722 fix: fix error when VCAP is empty in collect
  transformer/cloudfoundrytransformer.go
  types/collection/cfapps.go
Labels: fix

#723 fix: fix dockerfilepath and contextpath in dockerfileparser
  transformer/dockerfile/dockerfileparsertransformer.go
  transformer/kubernetes/apiresource/pipeline.go
Labels: fix

#724 feat: VCAP variables as springboot properties
  common/constants.go
  transformer/cloudfoundrytransformer.go
  transformer/dockerfile/dockerfileparsertransformer.go
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/dockerfilegenerator/java/springbootutils.go
  types/ir/ir.go
  types/transformer/artifacts/cloudfoundry.go
Labels: feat

#726 fix: fix strategic patch commit of podspec in ir
  transformer/cloudfoundrytransformer.go
  transformer/dockerfile/dockerfileparsertransformer.go
  transformer/dockerfilegenerator/java/springbootutils.go
  types/ir/ir.go
Labels: fix

#725 feat: Created a secret for all Cf VCAP environments
  common/constants.go
  common/utils.go
  transformer/cloudfoundrytransformer.go
  transformer/dockerfilegenerator/java/springbootutils.go
Labels: feat

#727 chore: update dependency versions
  go.mod
  go.sum
  types/qaengine/config.go
Labels: chore

#730 fix: remove incorrect info log in gradle parser
  transformer/dockerfilegenerator/java/gradle/gradleparser.go
Labels: fix

#735 fix: Fix error when username/password is entered for registry auth
  assets/inbuilt/transformers/kubernetes/parameterizer/parameterizer.yaml
  common/constants.go
  common/globals.go
  common/pathsofinterest.go
  common/utils.go
  lib/planner.go
  qaengine/defaultengine_test.go
  transformer/compose/v1v2.go
  transformer/compose/v3.go
  transformer/containerimage/containerimagespushscripttransformer.go
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/kubernetes/apiresource/storage.go
  transformer/kubernetes/apiresource/triggertemplate.go
  transformer/kubernetes/irpreprocessor/registrypreprocessor.go
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizer/types.go
  transformer/kubernetes/parameterizertransformer.go
  types/qaengine/commonqa/commonqa.go
Labels: fix

#736 feat: Allow password persistence with flag and prevent password question repetition
  cmd/commands/flags.go
  cmd/commands/plan.go
  cmd/commands/transform.go
  cmd/commands/utils.go
  qaengine/cliengine.go
  qaengine/engine.go
  qaengine/storeengine.go
  qaengine/storeengine_test.go
  transformer/kubernetes/irpreprocessor/registrypreprocessor.go
  types/qaengine/cache.go
  types/qaengine/cache_test.go
  types/qaengine/config.go
Labels: feat

#737 feat: Choose containerization option which matches servicename in cf if available
  transformer/containerizer.go
Labels: feat

#731 feat: Add more gradle property extraction capabilities
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/earanalyser/ear.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/gradle/gradle.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/gradle/templates/Dockerfile.gradle-build
  assets/inbuilt/transformers/dockerfilegenerator/java/jar/jar.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/jboss/jboss.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/jboss/templates/Dockerfile.jboss
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/liberty.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/mappings/javalibertyimagemappings.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/templates/Dockerfile.liberty
  assets/inbuilt/transformers/dockerfilegenerator/java/mappings/javapackageversions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/maven/maven.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/maven/templates/Dockerfile.maven-build
  assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat
  assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/tomcat.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/waranalyser/war.yaml
  transformer/dockerfilegenerator/java/earanalyser.go
  transformer/dockerfilegenerator/java/gradle/gradleparser.go
  transformer/dockerfilegenerator/java/gradle/types.go
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/jaranalyser.go
  transformer/dockerfilegenerator/java/jboss.go
  transformer/dockerfilegenerator/java/liberty.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/dockerfilegenerator/java/tomcat.go
  transformer/dockerfilegenerator/java/utils.go
  transformer/dockerfilegenerator/java/waranalyser.go
  types/transformer/artifacts/gradle.go
Labels: feat

#738 fix: install correct java version and liberty version in the runner image
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/liberty.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/mappings/javalibertyimagemappings.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/templates/Dockerfile.liberty
  transformer/compose/composegenerator.go
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/golangdockerfiletransformer.go
  transformer/dockerfilegenerator/java/earanalyser.go
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/jaranalyser.go
  transformer/dockerfilegenerator/java/jboss.go
  transformer/dockerfilegenerator/java/liberty.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/dockerfilegenerator/java/tomcat.go
  transformer/dockerfilegenerator/java/waranalyser.go
  transformer/dockerfilegenerator/java/zuulanalyser.go
  transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
  transformer/external/executabletransformer.go
  transformer/external/starlarktransformer.go
  transformer/kubernetes/buildconfigtransformer.go
  transformer/kubernetes/knativetransformer.go
  transformer/kubernetes/kubernetestransformer.go
  transformer/kubernetes/kubernetesversionchangertransformer.go
  transformer/kubernetes/parameterizertransformer.go
  transformer/kubernetes/tektontransformer.go
Labels: fix

#739 fix: fix broken links in readme
  README.md
Labels: fix

#740 fix: Update the download link of Tomcat in Dockerfile template
  assets/filepermissions.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat
Labels: fix

#741 chore: remove documentation nav level
  cmd/commands/docs.go
Labels: chore

#742 refactor: move main.go to base directory
  Makefile
  cmd/collect.go
  cmd/docs.go
  cmd/flags.go
  cmd/plan.go
  cmd/root.go
  cmd/transform.go
  cmd/umask.go
  cmd/utils.go
  cmd/version.go
  main.go
Labels: refactor

#743 feat: name transformer config yaml as transformer.yaml
  assets/filepermissions.yaml
  assets/inbuilt/transformers/cloudfoundry/transformer.yaml
  assets/inbuilt/transformers/compose/composeanalyser/transformer.yaml
  assets/inbuilt/transformers/compose/composegenerator/transformer.yaml
  assets/inbuilt/transformers/containerimagespushscript/templates/pushimages.bat
  assets/inbuilt/transformers/containerimagespushscript/templates/pushimages.sh
  assets/inbuilt/transformers/containerimagespushscript/transformer.yaml
  assets/inbuilt/transformers/dockerfile/dockerfiledetector/transformer.yaml
  assets/inbuilt/transformers/dockerfile/dockerfileparser/transformer.yaml
  assets/inbuilt/transformers/dockerfile/dockerimagebuildscript/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/dotnetcore/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/golang/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/earanalyser/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/earrouter/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/gradle/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/jar/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/jboss/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/liberty/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/maven/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/tomcat/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/waranalyser/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/warrouter/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/java/zuul/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/nodejs/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/php/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/python/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/ruby/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/rust/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/windows/winconsole/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/windows/winsilverlightweb/transformer.yaml
  assets/inbuilt/transformers/dockerfilegenerator/windows/winweb/transformer.yaml
  assets/inbuilt/transformers/kubernetes/buildconfig/transformer.yaml
  assets/inbuilt/transformers/kubernetes/clusterselector/transformer.yaml
  assets/inbuilt/transformers/kubernetes/knative/transformer.yaml
  assets/inbuilt/transformers/kubernetes/kubernetes/transformer.yaml
  assets/inbuilt/transformers/kubernetes/kubernetesversionchanger/transformer.yaml
  assets/inbuilt/transformers/kubernetes/parameterizer/parameterizers/replicas.yaml
  assets/inbuilt/transformers/kubernetes/parameterizer/transformer.yaml
  assets/inbuilt/transformers/kubernetes/tekton/transformer.yaml
  assets/inbuilt/transformers/readmegenerator/transformer.yaml
Labels: feat

#744 fix: Bug fixes for windows containerization
  assets/inbuilt/transformers/dockerfilegenerator/windows/winconsole/templates/Dockerfile
  assets/inbuilt/transformers/dockerfilegenerator/windows/winsilverlightweb/templates/Dockerfile
  assets/inbuilt/transformers/dockerfilegenerator/windows/winweb/templates/Dockerfile
  transformer/dockerfilegenerator/windows/utils.go
Labels: fix

#746 feat: Exposed temp path in starlark transformer
  transformer/external/starlarktransformer.go
Labels: feat
