Repository konveyor/move2kube, pull requests merged in 2022-11, with the labels that each got.

#891 feat: add a transformer to generate OLM specific yamls to install operators
  Makefile
  assets/built-in/transformers/cnb/transformer.yaml
  assets/built-in/transformers/kubernetes/operator/templates/README.md
  assets/built-in/transformers/kubernetes/operator/templates/subscription.yaml
  assets/built-in/transformers/kubernetes/operator/transformer.yaml
  assets/built-in/transformers/kubernetes/operatorsfromtca/Dockerfile
  assets/built-in/transformers/kubernetes/operatorsfromtca/detect.py
  assets/built-in/transformers/kubernetes/operatorsfromtca/transform.py
  assets/built-in/transformers/kubernetes/operatorsfromtca/transformer.yaml
  assets/filepermissions.yaml
  cmd/transform.go
  common/testdata/utf8and16bom/launchSettings.json
  common/utils.go
  common/utils_test.go
  environment/container/container.go
  environment/container/dockerengine.go
  environment/container/utils.go
  environment/environment.go
  environment/error.go
  environment/local.go
  environment/peercontainer.go
  environment/types.go
  filesystem/processor.go
  filesystem/templatecopy.go
  go.mod
  lib/transformer.go
  transformer/cnbcontainerizer.go
  transformer/external/executabletransformer.go
  transformer/kubernetes/kubernetestransformer.go
  transformer/kubernetes/operatortransformer.go
  transformer/transformer.go
  transformer/utils.go
  types/environment/container.go
  types/operator/operator.go
  types/transformer/artifact.go
Labels: feat

#909 fix: bug where the .dll filename was normalized when it shouldn't be in the Dockerfiles generated for Dot Net Core
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
  types/source/dotnet/csproj.go
Labels: fix

#910 chore: remove obsolte base_directory_detect from the starlark transformer
  transformer/external/starlarktransformer.go
Labels: chore

#912 fix: IR config was not getting properly unmarshalled leading to empty containers in the deployment yamls
  common/utils.go
  qaengine/engine.go
  transformer/kubernetes/apiresource/storage.go
Labels: fix

#914 feat: Support installing Move2Kube using the installation script on Power, s390x and arm64 systems
  scripts/install.sh
Labels: feat

#904 feat: Update the NodeJS Dockerfilegenerator transformer and Dockerfile template to support multi-arch build
  assets/built-in/transformers/dockerfilegenerator/mappings/nodeversions.yaml
  assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
  transformer/dockerfilegenerator/nodejsdockerfiletransformer.go
Labels: feat

#916 fix: detect the highest dot net framework version among child projects to use in the build stage
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
Labels: fix

#907 feat: Added containerized tranformer input/output configurability
  environment/environment.go
  environment/local.go
  environment/peercontainer.go
  transformer/cnbcontainerizer.go
  transformer/external/executabletransformer.go
Labels: feat

#918 fix: when the user specifies a replicas other than 2 it is not properly reflected in the Helm chart values.yaml
  assets/built-in/transformers/kubernetes/parameterizer/parameterizers/replicas.yaml
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizer/types.go
  transformer/kubernetes/parameterizer/utils.go
  transformer/kubernetes/parameterizertransformer.go
Labels: fix

#917 fix: Fix to enable health check on admin port from operator deployment
  assets/built-in/transformers/dockerfilegenerator/java/jboss/templates/Dockerfile.jboss
Labels: fix

#920 fix: use forward slashes for paths in Dockerfiles because backward slash is a special character
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
Labels: fix
