Repository konveyor/move2kube, pull requests merged in 2022-03, with the labels that each got.

#775 fix: empty metadata.name or service name when transforming docker compose with volume
  transformer/compose/v3.go
  transformer/kubernetes/apiresource/storage.go
  transformer/kubernetes/k8sschema/utils.go
  transformer/kubernetes/parameterizertransformer.go
  transformer/transformer.go
Labels: fix

#777 fix: fix docker compose v2 parsing warning from v3 parser
  transformer/compose/v3.go
Labels: fix

#779 chore: change the warning messages to give path to the csproj file that failed version check
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/windows/consoleappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/silverlightwebappdockerfilegenerator.go
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
  types/source/dotnet/csproj.go
Labels: chore

#780 fix: warnings when trying to get files from non existent directory src/main/resources
  common/utils.go
  transformer/dockerfilegenerator/java/springbootutils.go
Labels: fix

#781 fix: Update the template to skip the checkstyle validation
  assets/built-in/transformers/dockerfilegenerator/java/maven/templates/Dockerfile.maven-build
Labels: fix

#782 fix: gradle artifact name is wrong on spring pet-clinic sample app
  transformer/dockerfilegenerator/java/gradleanalyser.go
Labels: fix

#783 fix: Query output for multi-select marshalling crash addressed
  transformer/external/starlarktransformer.go
Labels: fix

#784 feat: add another e2e test for move2kube CLI with enterprise app
  .github/workflows/e2etest.yml
Labels: feat

#785 fix: Normalize the git repo name for the service name
  transformer/servicenamer.go
Labels: fix

#786 fix: detection of port not working for spring boot application.yaml
  common/utils.go
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/dockerfilegenerator/java/springbootutils.go
Labels: fix

#787 fix: warning about service directory path even when it's not a spring boot app
  transformer/dockerfilegenerator/java/mavenanalyser.go
Labels: fix

#788 fix: check the parent poms as well in a multi-module project to find spring boot dependencies
  transformer/dockerfilegenerator/java/mavenanalyser.go
  types/transformer/artifacts/java.go
Labels: fix

#789 fix: parameters in parameterizer templates were not being filled in with the correct values
  transformer/kubernetes/parameterizer/parameterizer.go
Labels: fix

#791 fix: allow specifying the environments to parameterize for
  assets/built-in/transformers/kubernetes/parameterizer/transformer.yaml
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizer/parameterizer_test.go
  transformer/kubernetes/parameterizertransformer.go
Labels: fix

#792 fix: add java 7 and 8 to the list of supported java package versions
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/builddockerimages.sh
  assets/built-in/transformers/dockerfilegenerator/java/mappings/javapackageversions.yaml
  transformer/dockerfilegenerator/java/jaranalyser.go
  transformer/dockerfilegenerator/java/utils.go
Labels: fix
