Repository konveyor/move2kube, pull requests merged in 2022-02, with the labels that each got.

#747 feat: Added name to the metadata of the cf collect
  collector/cfappscollector.go
  collector/cfservicescollector.go
Labels: feat

#748 fix: prevent cf transformer creation of ir when containerizing app
  transformer/cloudfoundrytransformer.go
Labels: fix

#749 fix: remove assumption of port 8080 for cf apps when no port is found
  transformer/cloudfoundrytransformer.go
Labels: fix

#750 feat: sort transformers to ensure order of execution
  cmd/transform.go
  lib/planner.go
  lib/transformer.go
  transformer/containerizer.go
  transformer/routertransformer.go
  transformer/transformer.go
  types/plan/plan.go
Labels: feat

#751 fix: fix transformers warning
  lib/transformer.go
Labels: fix

#752 feat: Add support for mvnw
  assets/built-in/transformers/dockerfilegenerator/java/gradle/templates/Dockerfile.gradle-build
  assets/built-in/transformers/dockerfilegenerator/java/maven/templates/Dockerfile.maven-build
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  types/transformer/artifacts/maven.go
Labels: feat

#753 chore: now website will trigger homebrew after updating releaseinfo.json
  .github/workflows/publish.yml
Labels: chore

#755 fix: warn when plan is present and source or customization is specified
  cmd/transform.go
Labels: fix

#756 fix: bug where finalName in Maven profiles was not being used
  transformer/dockerfilegenerator/java/mavenanalyser.go
Labels: fix

#757 feat: prioritize deployment over deploymentconfig if both are supported by a cluster
  transformer/kubernetes/apiresource/deployment.go
Labels: feat

#758 feat: Add support for containerize only preset
  assets/built-in/presets/containerizeonly.yaml
  assets/built-in/transformers/containerimagespushscript/transformer.yaml
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/transformer.yaml
  assets/filepermissions.yaml
Labels: feat

#759 feat: Collect metadata name
  collector/cfappscollector.go
  collector/cfservicescollector.go
  common/utils.go
Labels: feat

#761 feat: Allow clusterip only service
  common/constants.go
  transformer/dockerfilegenerator/java/zuulanalyser.go
  transformer/kubernetes/apiresource/service.go
  transformer/kubernetes/irpreprocessor/ingresspreprocessor.go
  transformer/kubernetes/irpreprocessor/mergepreprocessor.go
Labels: feat

#762 feat: Split Service option question into two
  transformer/kubernetes/apiresource/service.go
  transformer/kubernetes/irpreprocessor/ingresspreprocessor.go
  types/ir/ir.go
Labels: feat

#763 feat: trigger end to end test in move2kube-tests repo for transforming and deploying language platforms in a cluster
  .github/workflows/e2etest.yml
Labels: feat

#764 fix: fix containerized transformer path mapping
  environment/container/container.go
  environment/container/dockerengine.go
  environment/container/fileinfo.go
  environment/environment.go
  environment/local.go
  environment/peercontainer.go
Labels: fix

#765 fix: Fix panic error in gradle transformer
  transformer/dockerfilegenerator/java/gradle/types.go
Labels: fix

#766 fix: panic during QA when transforming some apps like train-ticket
  common/utils.go
  transformer/dockerfilegenerator/pythondockerfiletransformer.go
Labels: fix

#769 fix: fix container name being empty in compose
  transformer/compose/v1v2.go
  transformer/compose/v3.go
Labels: fix

#767 fix: fix tekton ingress creation
  transformer/kubernetes/apiresource/service.go
  transformer/kubernetes/tektontransformer.go
Labels: fix

#771 fix: check if sudo is installed in the install script
  scripts/install.sh
Labels: fix

#772 feat: add "generated by" section to the output README to show which version of Move2Kube generated the artifacts
  assets/built-in/transformers/readmegenerator/templates/Readme.md
  transformer/readmetransformer.go
Labels: feat

#773 fix: Log error and continue on parameterize failure of single files
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizertransformer.go
Labels: fix
