Repository konveyor/move2kube, pull requests merged in 2022-10, with the labels that each got.

#883 chore: update the go.mod file to fix minor issues
  go.mod
  go.sum
  transformer/transformer.go
Labels: chore

#889 fix: deselect the console and silverlight transformer by default to avoid conflicts with dotnet webapp transformer
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  Makefile
  assets/built-in/transformers/dockerfilegenerator/windows/winconsole/transformer.yaml
  assets/built-in/transformers/dockerfilegenerator/windows/winsilverlightweb/transformer.yaml
  cmd/plan.go
  cmd/transform.go
  lib/planner.go
  lib/transformer.go
  transformer/transformer.go
  types/plan/plan.go
Labels: fix

#890 feat: allow changing where the scripts folder gets generated
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.sh
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.sh
  transformer/containerimage/containerimagespushscripttransformer.go
  transformer/dockerfile/dockerfilebuildscripttransformer.go
Labels: feat

#894 chore: errors were not beind displayed properly in a few places
  cmd/collect.go
  environment/container/dockerengine_test.go
Labels: chore

#895 fix: the rust transformer was not detecting the rust service in language-platforms
  transformer/dockerfilegenerator/pythondockerfiletransformer.go
  transformer/dockerfilegenerator/rustdockerfiletransformer.go
  transformer/kubernetes/k8sschema/utils.go
Labels: fix

#897 chore: print better error when the transformer specified in the config is not found
  transformer/transformer.go
Labels: chore

#898 feat: add validator and retries to qa engine
  common/sshkeys/sshkeys.go
  environment/container/container.go
  lib/transformer.go
  qaengine/cliengine.go
  qaengine/defaultengine.go
  qaengine/defaultengine_test.go
  qaengine/engine.go
  qaengine/httprestengine.go
  qaengine/storeengine.go
  qaengine/storeengine_test.go
  transformer/cloudfoundrytransformer.go
  transformer/dockerfilegenerator/dotnet/utils.go
  transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  transformer/dockerfilegenerator/java/utils.go
  transformer/dockerfilegenerator/phpdockerfiletransformer.go
  transformer/dockerfilegenerator/pythondockerfiletransformer.go
  transformer/dockerfilegenerator/windows/webappdockerfilegenerator.go
  transformer/external/starlarktransformer.go
  transformer/kubernetes/apiresource/service.go
  transformer/kubernetes/clusterselector.go
  transformer/kubernetes/irpreprocessor/ingresspreprocessor.go
  transformer/kubernetes/irpreprocessor/registrypreprocessor.go
  transformer/kubernetes/tektontransformer.go
  transformer/routertransformer.go
  transformer/transformer.go
  types/qaengine/commonqa/commonqa.go
  types/qaengine/problem.go
  types/qaengine/qaengine.go
  types/qaengine/qagrpc/fetchanswer.pb.go
  types/qaengine/qagrpc/fetchanswer.proto
  types/qaengine/qagrpc/fetchanswer_grpc.pb.go
Labels: feat

#899 fix: return a HTTP error status code when the answer is invalid
  qaengine/defaultengine.go
  qaengine/httprestengine.go
  types/qaengine/problem.go
Labels: fix

#900 feat: Remove container runtime question. Allow overriding container runtime while running build or push scripts through env variable.
  assets/built-in/transformers/containerimagespushscript/templates/pushimages.bat
  assets/built-in/transformers/containerimagespushscript/templates/pushimages.sh
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.sh
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.sh
  common/constants.go
  transformer/containerimage/containerimagespushscripttransformer.go
  transformer/dockerfile/dockerfilebuildscripttransformer.go
  types/qaengine/commonqa/commonqa.go
Labels: feat

#885 feat: File input/output interface for containerized transformers
  environment/environment.go
  environment/types.go
  transformer/cnbcontainerizer.go
  transformer/external/executabletransformer.go
  transformer/transformer.go
  types/environment/exec.go
Labels: feat

#901 fix: config could contain invalid values not present in the options of select and multi-select questions
  common/pathconverters/pathconverters.go
  common/utils.go
  qaengine/storeengine.go
Labels: fix

#903 feat: Add instruction with examples on how to invoke the build and push images scripts
  assets/built-in/transformers/containerimagespushscript/templates/pushimages.bat
  assets/built-in/transformers/containerimagespushscript/templates/pushimages.sh
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.sh
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.sh
Labels: feat

#906 feat: Added tranformer input type
  transformer/external/executabletransformer.go
  types/transformer/input.go
Labels: feat

#905 fix: Resolve permission denied issue on OpenShift cluster for NodeJS
  assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
Labels: fix
