Repository konveyor/move2kube, pull requests merged in 2022-09, with the labels that each got.

#858 feat: xml reader and query functions for starlark
  go.mod
  go.sum
  transformer/external/starlarktransformer.go
Labels: feat

#859 fix: detect the java and app version for generating proper dockerfiles
  assets/built-in/transformers/dockerfilegenerator/java/mappings/javapackageversions.yaml
  transformer/dockerfilegenerator/java/gradleanalyser.go
Labels: fix

#863 feat: Generate binaries for s390x/Power platforms
  Makefile
Labels: feat

#865 feat: add crypto utils, template functions and ibm vpc certificate
  common/cryptoutils.go
  filesystem/templatecopy.go
Labels: feat, do-not-merge/work-in-progress

#867 feat: add resources dir starlark custom variable
  transformer/external/starlarktransformer.go
Labels: feat

#868 feat: add output_dir starlark custom variable
  transformer/external/starlarktransformer.go
Labels: feat

#870 feat: add archive utils with compression options
  common/constants.go
  common/utils.go
  environment/container/dockerengine.go
  environment/container/utils.go
  filesystem/templatecopy.go
Labels: feat, do-not-merge/hold

#871 feat: add starlark custom functions for crypto and archive utils
  transformer/external/starlarktransformer.go
Labels: feat

#872 fix: use snake case for starlark custom functions
  transformer/external/starlarktransformer.go
Labels: fix

#873 fix: function mismatches in starlark code and fix error messages
  transformer/external/starlarktransformer.go
Labels: fix

#874 fix: support archiving both file path and directory path
  common/utils.go
  environment/container/dockerengine.go
  environment/container/utils.go
Labels: fix

#876 fix: fail when none of the source or customizations folder is given
  cmd/plan.go
  cmd/transform.go
Labels: fix, do-not-merge

#878 feat: let the user decide if they want planning to fail if no services are detected
  cmd/plan.go
  common/constants.go
Labels: feat
