Repository konveyor/move2kube, pull requests merged in 2022-12, with the labels that each got.

#922 fix: partially fixes the issue with the windows build images script
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
Labels: fix

#924 fix: Prevent docker build from failing if .npm folder is missing
  assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
Labels: fix

#923 fix: look for external services in CfApps file instead of the CfServices file
  assets/built-in/transformers/kubernetes/operatorsfromtca/Dockerfile
  assets/built-in/transformers/kubernetes/operatorsfromtca/cfservices.yaml
  assets/built-in/transformers/kubernetes/operatorsfromtca/detect.py
  assets/built-in/transformers/kubernetes/operatorsfromtca/preprocess.py
  assets/built-in/transformers/kubernetes/operatorsfromtca/transform.py
  assets/filepermissions.yaml
Labels: fix

#926 fix: Resolve the unsupported build system issue with the windows build images batch scripts
  assets/built-in/transformers/containerimagespushscript/templates/pushimages.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.bat
Labels: fix

#929 fix: Do not add the image pull secret to the service IR if selected no authentication
  transformer/kubernetes/irpreprocessor/registrypreprocessor.go
Labels: fix

#931 chore: update the message shown when the output directory exists
  cmd/utils.go
Labels: chore

#935 chore: some minor fixes to handle errors properly in the starlark transformer
  transformer/compose/composeanalyser.go
  transformer/external/starlarktransformer.go
  transformer/kubernetes/apiresource/apiresource.go
  transformer/kubernetes/apiresource/storage.go
  transformer/kubernetes/apiresource/utils.go
  transformer/kubernetes/kubernetestransformer.go
  transformer/transformer.go
Labels: chore

#936 fix: K8s resource limits set in Starlark transformers were not being unmarshalled correctly
  common/utils.go
  transformer/kubernetes/apiresource/storage.go
Labels: fix

#941 feat: Do not use default values in the Kubernetes yamls
  assets/built-in/transformers/kubernetes/argocd/transformer.yaml
  assets/built-in/transformers/kubernetes/buildconfig/transformer.yaml
  assets/built-in/transformers/kubernetes/knative/transformer.yaml
  assets/built-in/transformers/kubernetes/kubernetes/transformer.yaml
  assets/built-in/transformers/kubernetes/kubernetesversionchanger/transformer.yaml
  assets/built-in/transformers/kubernetes/tekton/transformer.yaml
  transformer/kubernetes/apiresource/utils.go
  transformer/kubernetes/argocdtransformer.go
  transformer/kubernetes/buildconfigtransformer.go
  transformer/kubernetes/k8sschema/converters.go
  transformer/kubernetes/knativetransformer.go
  transformer/kubernetes/kubernetestransformer.go
  transformer/kubernetes/kubernetesversionchangertransformer.go
  transformer/kubernetes/tektontransformer.go
Labels: feat
