Repository konveyor/move2kube, pull requests merged in 2023-04, with the labels that each got.

#1003 fix: panic when run on docker compose single service sample because []interface{} is not []string
  transformer/compose/composeanalyser.go
Labels: fix

#1006 fix: panic when placing dynamic params in IR because the "artifact.configs" is nil at some points
  transformer/kubernetes/kubernetestransformer.go
Labels: fix

#1001 fix: Do not copy file from non-existent builder image in Jar-run Dockerfile
  assets/built-in/transformers/dockerfilegenerator/java/jar/templates/Dockerfile.jar-run
  common/constants.go
  transformer/dockerfilegenerator/java/jaranalyser.go
Labels: fix

#1007 feat: add a flag to limit the maximum number of iterations
  cmd/flags.go
  cmd/transform.go
  lib/transformer.go
  transformer/transformer.go
Labels: feat

#999 test: unit test for utils.go file in filesystem package
  filesystem/test_data/copyfile/test.txt
  filesystem/utils_test.go
Labels: lfx-project, test

#1008 fix: remove temp directories on interrupt
  lib/transformer.go
Labels: fix

#1009 feat: make the graph more deterministic by sorting the vertices
  cmd/graph.go
  graph/layout.go
Labels: feat

#1011 fix: update image to ubi8 and hello-world
  environment/container/dockerengine_test.go
  environment/container/podmanengine_test.go
Labels: fix, lfx-project

#1012 test: unit tests for utils.go file in lib package
  lib/utils_test.go
Labels: lfx-project, test

#1014 fix: the graph to show mandatory passthrough transformers on a new line
  graph/layout.go
  types/graph/graph.go
Labels: fix

#1015 feat: Use latest version of go-cfclient v2 for move2kube collect
  collector/cfutils.go
  go.mod
  go.sum
  types/collection/cfapps.go
  types/collection/cfservices.go
Labels: feat

#1017 fix: Resolve docker build failure of NodeJS application
  assets/built-in/transformers/dockerfilegenerator/nodejs/templates/Dockerfile
Labels: fix

#998 feat: allow git remote paths to be provided as source to move2kube
  cmd/plan.go
  cmd/transform.go
  common/constants.go
  common/pathsofinterest.go
  common/utils.go
  common/vcs/git.go
  common/vcs/vcs.go
  lib/planner.go
  main.go
  types/plan/planutils.go
Labels: feat, lfx-project

#1019 fix: remove external transformer temp directories on interrupt
  lib/transformer.go
  transformer/external/executabletransformer.go
Labels: fix

#1005 feat: Configmap creation for compose
  common/constants.go
  transformer/compose/utils.go
  transformer/compose/v1v2.go
  transformer/compose/v3.go
Labels: feat
