Repository konveyor/move2kube, pull requests merged in 2023-07, with the labels that each got.

#1056 feat: input config files from http links
  cmd/plan.go
  cmd/transform.go
  common/download/download.go
  common/download/httpdownload.go
  common/utils.go
  qaengine/engine.go
Labels: feat

#1055 fix: Resolve no clean images detected issue; Remove extra blank image name
  collector/imagescollector.go
Labels: fix

#1065 docs: Update the documentation link in Readme file
  README.md
Labels: docs
