Repository konveyor/move2kube, pull requests merged in 2023-05, with the labels that each got.

#1031 feat: Allow remote paths to be specified for customisations or -c flag
  common/constants.go
  common/vcs/vcs.go
  lib/planner.go
  lib/utils.go
  types/plan/planutils.go
Labels: feat

#1034 fix: better error messages while unmarshalling a K8s resource YAML
  transformer/kubernetes/k8sschema/utils.go
Labels: fix

#1032 docs: add git support as part of usage information
  cmd/plan.go
  cmd/transform.go
Labels: docs

#1029 test: add unit tests for ir.go file
  types/ir/ir_test.go
  types/ir/testdata/conbuild.yaml
  types/ir/testdata/conimage.yaml
  types/ir/testdata/ir.yaml
  types/ir/testdata/mergedSt.yaml
  types/ir/testdata/merged_service.yaml
  types/ir/testdata/mergedconbuild.yaml
  types/ir/testdata/mergedconimage.yaml
  types/ir/testdata/mergedir.yaml
  types/ir/testdata/newconbuild.yaml
  types/ir/testdata/newconimage.yaml
  types/ir/testdata/newir.yaml
  types/ir/testdata/newst.yaml
  types/ir/testdata/nservice.yaml
  types/ir/testdata/s.yaml
  types/ir/testdata/service.yaml
Labels: lfx-project, test

#1027 feat: allow git remote paths for move2kube generated outputs
  cmd/transform.go
  common/constants.go
  common/vcs/git.go
  common/vcs/vcs.go
  lib/planner.go
  lib/transformer.go
Labels: feat

#1038 test: git vcs functions
  common/vcs/git_test.go
Labels: test

#1037 fix: follow git branch naming convention based on docs.github.com
  common/vcs/git.go
Labels: fix

#1028 fix: fail when path is not a directory for peercontainer upload/download
  environment/peercontainer.go
Labels: fix

#1026 feat: Allow to collect only selected CF apps metadata through yaml; Support query depth parameter and spaceguid as filters
  collector/cfappscollector.go
  collector/cfutils.go
  collector/cfutils_test.go
  common/utils.go
  transformer/cloudfoundrytransformer.go
  types/collection/cfapps.go
Labels: feat
