Repository konveyor/move2kube, pull requests merged in 2023-01, with the labels that each got.

#937 feat: Support for user-defined output path for executable transform
  common/utils.go
  transformer/external/executabletransformer.go
Labels: feat

#944 fix: Resolve panic error in Zuul analyser for path not ending with double asterisk
  transformer/dockerfilegenerator/java/zuulanalyser.go
Labels: fix

#945 fix: QA handlers would block the POST request indefinitely in some cases, near the end of transform
  graph/server.go
  qaengine/httprestengine.go
Labels: fix

#946 fix: posting a solution to the qa server was blocking till the channel cleared
  qaengine/httprestengine.go
Labels: fix

#943 feat: Update the Golang Dockerfilegenerator transformer to support multi-arch build
  assets/built-in/transformers/dockerfilegenerator/golang/mappings/golangversions.yaml
  assets/built-in/transformers/dockerfilegenerator/golang/templates/Dockerfile
  assets/built-in/transformers/dockerfilegenerator/golang/transformer.yaml
  assets/filepermissions.yaml
  transformer/dockerfilegenerator/golangdockerfiletransformer.go
Labels: feat

#947 fix: Add execute permission to the buildandpushimages_multiarch.bat file
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.bat
Labels: fix

#948 chore: better error messages and minor bug fixes
  lib/planner.go
  lib/utils.go
  transformer/transformer.go
  transformer/utils.go
  types/transformer/transformer.go
Labels: chore

#950 fix: crashes when pom file build section is absent
  transformer/dockerfilegenerator/java/gradleanalyser.go
  transformer/dockerfilegenerator/java/mavenanalyser.go
  types/source/maven/pom.go
Labels: fix

#951 fix: bug where registry url was being asked multiple times when selecting "Other" as the option
  qaengine/defaultengine.go
  qaengine/engine.go
  qaengine/httprestengine.go
  qaengine/storeengine.go
  types/qaengine/commonqa/commonqa.go
  types/qaengine/problem.go
Labels: fix

#952 feat: obfuscate passwords by base64 encoding them before writing to config and cache
  cmd/transform.go
  qaengine/engine.go
  types/qaengine/cache.go
  types/qaengine/config.go
  types/qaengine/qaengine.go
Labels: feat

#953 feat: Added presets for dockerfile and docker-compose configs
  assets/built-in/presets/analyze-docker-compose-only.yaml
  assets/built-in/presets/containerize-only.yaml
  assets/built-in/presets/docker-file-only.yaml
  assets/built-in/presets/enable-containerized-transformers.yaml
  assets/built-in/presets/use-podman-in-scripts.yaml
  assets/filepermissions.yaml
Labels: feat

#955 feat: Loosened the paramaterization detect check
  transformer/kubernetes/k8sschema/utils.go
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizertransformer.go
Labels: feat

#956 chore: fix typo
  transformer/dockerfilegenerator/java/mavenanalyser.go
Labels: chore
