Repository konveyor/move2kube, pull requests merged in 2023-09, with the labels that each got.

#1069 fix: take destNamespace from user
  common/constants.go
  transformer/kubernetes/apiresource/argocdapplication.go
Labels: fix

#1087 fix: panic when a port is not specified in an Openshift Route
  transformer/kubernetes/apiresource/service.go
Labels: fix

#1090 fix: add DaemonSet to deployment supported kinds
  transformer/kubernetes/apiresource/deployment.go
Labels: fix

#1092 ci: remove operator repo from the release pipeline. UI repo has the operator now
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: ci

#1093 test: add a flag to generate the CPU profile for the transform command
  cmd/flags.go
  cmd/transform.go
Labels: test

#1078 feat: Add an option to let the user provide the entire key PEM data as the answer
  common/sshkeys/sshkeys.go
Labels: feat

#1094 fix: the logic to accept a user provided PEM formatted SSH private key for each git repo domain
  common/sshkeys/sshkeys.go
Labels: fix
