Repository konveyor/move2kube, pull requests merged in 2023-03, with the labels that each got.

#969 fix: set-output throws error in ci/cd starting June 2023
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: fix

#975 feat: Add read_properties, write_properties and get_dir to the builtin starlark modules
  transformer/external/starlarktransformer.go
Labels: feat

#985 fix: bug where merging slice of interfaces introduced nils in the result
  common/deepcopy/merge.go
  common/deepcopy/merge_test.go
Labels: fix

#986 feat: add ability to provide extra parameterizers at runtime
  transformer/kubernetes/kubernetestransformer.go
  transformer/kubernetes/parameterizer/parameterizer.go
  transformer/kubernetes/parameterizertransformer.go
  transformer/transformer.go
  transformer/utils.go
Labels: feat

#988 fix: Normalized the secret and configmap names in v3 compose
  transformer/compose/v3.go
Labels: fix

#987 feat: Added read binary in starlark transformer
  transformer/external/starlarktransformer.go
  transformer/kubernetes/apiresource/storage.go
Labels: feat

#989 feat: Add create_dir, copy_dir and remove modules to the builtin starlark transformer
  go.mod
  go.sum
  transformer/external/starlarktransformer.go
Labels: feat

#993 feat: Add docker-compose context to be used in the ComposeAnalyser transform
  transformer/compose/composeanalyser.go
Labels: feat

#994 test: unit tests for dockerengine.go file in container package
  environment/container/dockerengine_test.go
  environment/container/testdata/buildimage/dockerfile
  environment/container/testdata/dirstocopy/dir1/test1.txt
  environment/container/testdata/dirstocopy/dir2/test2.txt
Labels: lfx-project, test

#997 test: unit tests for podmanengine.go file in container package
  environment/container/dockerengine_test.go
  environment/container/podmanengine.go
  environment/container/podmanengine_test.go
Labels: lfx-project, test
