Repository konveyor/move2kube, pull requests merged in 2023-06, with the labels that each got.

#1040 test: test isGitBranch function
  common/vcs/git_test.go
Labels: test

#1042 fix: git url parse
  common/utils.go
  transformer/kubernetes/apiresource/buildconfig.go
  transformer/kubernetes/apiresource/pipeline.go
  transformer/kubernetes/buildconfigtransformer.go
  transformer/kubernetes/tektontransformer.go
Labels: fix

#1044 feat: upgrade tekton triggers to v1beta1
  transformer/kubernetes/apiresource/eventlistener.go
  transformer/kubernetes/apiresource/triggerbinding.go
  transformer/kubernetes/apiresource/triggertemplate.go
  transformer/kubernetes/tektontransformer.go
Labels: feat

#1045 feat: add workspaces to Tekton pipeline for git repo creds and registry creds
  common/constants.go
  common/utils.go
  transformer/dockerfile/dockerfileparsertransformer.go
  transformer/kubernetes/apiresource/pipeline.go
  transformer/kubernetes/apiresource/triggertemplate.go
  transformer/kubernetes/irpreprocessor/registrypreprocessor.go
  types/ir/ir.go
Labels: feat

#1046 chore: tidy go.mod removing unused packages
  go.mod
Labels: chore

#1050 feat: add ability to fill a Golang template from a Starlark transformer
  common/utils.go
  transformer/external/starlarktransformer.go
Labels: feat

#1051 feat: add a field to allow force rebuilding of the image
  environment/environment.go
  environment/peercontainer.go
  types/environment/container.go
Labels: feat

#1053 fix: Resolve move2kube images collect error
  collector/imagescollector.go
Labels: fix
