Repository konveyor/move2kube, pull requests merged in 2023-08, with the labels that each got.

#1066 test: add tests for replicateProcessFileCallBack
  filesystem/replicator_test.go
  filesystem/test_data/replicator_test/destination_same.txt
  filesystem/test_data/replicator_test/emptyfile.txt
  filesystem/test_data/replicator_test/source_same.txt
Labels: test

#1068 fix: Update Documentation badge link
  README.md
Labels: fix

#1073 docs: fix GitHub indendation
  contributing.md
Labels: docs

#1072 refactor: rename "test_data" to "testdata" for consistency
  filesystem/replicator_test.go
  filesystem/templatecopy_test.go
  filesystem/testdata/copyfile/test.txt
  filesystem/testdata/replicator_test/destination_same.txt
  filesystem/testdata/replicator_test/emptyfile.txt
  filesystem/testdata/replicator_test/source_same.txt
  filesystem/testdata/template/test.yaml
  filesystem/testdata/template/test_filled.yaml
  filesystem/utils_test.go
Labels: refactor

#1075 fix: replace deprecated ioutil readfile function
  filesystem/replicator_test.go
Labels: fix

#1076 fix: Fix install script on Apple devices with Apple Silicon
  scripts/install.sh
Labels: fix

#1080 fix: key error from detect for operatorsfromtca transformer
  assets/built-in/transformers/kubernetes/operatorsfromtca/detect.py
Labels: fix

#1077 test: add tests for replicateDeletionCallback
  filesystem/replicator_test.go
  filesystem/testdata/src/empty.txt
Labels: test

#1085 fix: update 3rd party dependency to latest version to fix vuln CVE-2022-23648
  go.mod
  go.sum
Labels: fix
