Repository konveyor/move2kube, pull requests merged in 2024-01, with the labels that each got.

#1095 feat: pick cgo arg from env
  Makefile
Labels: feat, lfx-project

#1125 test: added test for mergeDeletionCallBack
  filesystem/merger_test.go
Labels: test

#1133 docs: add a OWNERS.md according to Konveyor rules
  OWNERS.md
Labels: docs

#1137 docs: add instructions for uninstalling CLI
  README.md
Labels: docs
