Repository konveyor/move2kube, pull requests merged in 2024-03, with the labels that each got.

#1126 fix: install openssh in Dockerfile in order to be able to clone repo using ssh keys
  Dockerfile
Labels: fix

#1152 fix: atomic.Int64 requires go1.19 otherwise breaks
  Dockerfile
  Makefile
  README.md
Labels: fix

#1153 fix: Update the QA categorization mappings file
  assets/built-in/qa/qamappings.yaml
Labels: fix

#1158 feat: Allow overriding the default QA Mappings file
  assets/built-in/qa/qamappings.yaml
  cmd/flags.go
  cmd/transform.go
  cmd/utils.go
  lib/planner.go
  lib/utils.go
  types/qaengine/qamapping.go
Labels: feat

#1156 fix: QA categories were being used only by the CLI engine
  qaengine/cliengine.go
  qaengine/engine.go
Labels: fix

#1160 fix: When the m2kignore file is removed from language_platforms.zip then in the UI only the Ruby service is detected
  transformer/dockerfilegenerator/rubydockerfiletransformer.go
Labels: fix

#1128 fix: add condition for version_metadata in Makefile
  Makefile
Labels: fix

#1129 test: added test for TestMergeProcessFileCallBack different content case
  filesystem/merger_test.go
Labels: test

#1162 fix: bug where all yaml files were treated as K8s yamls by the Parameterizer
  transformer/kubernetes/k8sschema/utils.go
  transformer/kubernetes/parameterizer/parameterizer.go
Labels: fix

#1163 fix: when using --qa-enable and --qa-disable the answers to disabled questions were not being added to the generated config file
  qaengine/engine.go
Labels: fix

#1165 fix: K8s version change transformer was not being run sometimes because Parameterizer was running first
  assets/built-in/transformers/kubernetes/kubernetesversionchanger/transformer.yaml
  assets/built-in/transformers/kubernetes/parameterizer/transformer.yaml
  common/utils.go
  transformer/transformer.go
Labels: fix

#1167 feat: add a flag to profile the heap memory
  cmd/flags.go
  cmd/transform.go
Labels: feat

#1169 fix: write out a heap memory profile immediately
  cmd/transform.go
Labels: fix
