Repository konveyor/move2kube, pull requests merged in 2024-07, with the labels that each got.

#1186 feat: improve git clone mechanism
  common/vcs/git.go
Labels: feat

#1188 test: cicd release failing with HTTP 404 error
  .github/workflows/release.yml
Labels: test

#1189 fix: http 404 status causes release cicd pipeline failure
  .github/workflows/release.yml
Labels: fix

#1190 ci: use the fixed version of artifact upload action to avoid http 404 error
  .github/workflows/release.yml
Labels: ci
