Repository konveyor/move2kube, pull requests merged in 2024-04, with the labels that each got.

#1157 feat: podman multiarch support
  assets/built-in/transformers/containerimagespushscript/templates/pushimages.sh
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.bat
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildandpushimages_multiarch.sh
  assets/built-in/transformers/dockerfile/dockerimagebuildscript/templates/buildimages.sh
  common/utils.go
  transformer/containerimage/containerimagespushscripttransformer.go
  transformer/dockerfile/dockerfilebuildscripttransformer.go
Labels: feat, lfx-project

#1172 feat: Support WASM external transformers using Wazero runtime
  go.mod
  go.sum
  transformer/external/executabletransformer.go
  transformer/external/wasmtransformer.go
  transformer/transformer.go
Labels: feat

#1178 ci: rename the custom github actions to use the new repo names
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
Labels: ci
